In [1]:
import mysql.connector
import pandas as pd

# Establish connection

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Admin@123",
    database="cab_booking_system"
)

# Load table into pandas DataFrame
rides_df = pd.read_sql("SELECT * FROM rides", conn)
rides_df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_5952\2310421437.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rides_df = pd.read_sql("SELECT * FROM rides", conn)

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,status,vehicle_id
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1
1,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2
2,3,79,40,Hinjewadi,Shivajinagar,2024-02-01 02:00:00,2024-02-01 02:20:00,121.44,completed,3
3,4,7,20,Wakad,Shivajinagar,2024-02-01 03:00:00,2024-02-01 03:20:00,310.31,completed,4
4,5,66,18,Kothrud,Wakad,2024-02-01 04:00:00,2024-02-01 04:20:00,311.30,completed,5

In [2]:
rides_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ride_id          300 non-null    int64
 1   customer_id      300 non-null    int64
 2   driver_id        300 non-null    int64
 3   pickup_location  300 non-null    object
 4   drop_location    300 non-null    object
 5   pickup_time      300 non-null    datetime64[ns]
 6   drop_time        270 non-null    datetime64[ns]
 7   fare             300 non-null    float64
 8   status           300 non-null    object
 9   vehicle_id       300 non-null    int64
dtypes: datetime64[ns](2), float64(1), int64(4), object(3)
memory usage: 23.6+ KB

In [3]:
rides_df.head()

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,status,vehicle_id
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1
1,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2
2,3,79,40,Hinjewadi,Shivajinagar,2024-02-01 02:00:00,2024-02-01 02:20:00,121.44,completed,3
3,4,7,20,Wakad,Shivajinagar,2024-02-01 03:00:00,2024-02-01 03:20:00,310.31,completed,4
4,5,66,18,Kothrud,Wakad,2024-02-01 04:00:00,2024-02-01 04:20:00,311.30,completed,5

In [4]:
rides_df.describe()

,ride_id,customer_id,driver_id,pickup_time,drop_time,fare,vehicle_id
count,300.000000,300.000000,300.000000,300,270,300.000000,300.000000
mean,150.500000,52.623333,26.696667,2024-03-30 11:54:12.666666752,2024-02-07 05:20:00,347.100500,25.500000
min,1.000000,1.000000,1.000000,2024-02-01 00:00:00,2024-02-01 00:20:00,80.200000,1.000000
25%,75.750000,26.000000,14.750000,2024-02-04 07:45:00,2024-02-04 02:35:00,228.837500,13.000000
50%,150.500000,56.000000,27.000000,2024-02-07 15:30:00,2024-02-07 05:20:00,339.440000,25.500000
75%,225.250000,81.000000,40.000000,2024-02-11 00:15:00,2024-02-10 08:05:00,467.580000,38.000000
max,300.000000,100.000000,50.000000,2026-04-01 12:33:10,2024-02-13 10:20:00,599.310000,50.000000
std,86.746758,31.041801,14.514829,NaN,NaN,143.266665,14.454981

In [5]:
rides_df.isnull().sum()

ride_id             0
customer_id         0
driver_id           0
pickup_location     0
drop_location       0
pickup_time         0
drop_time          30
fare                0
status              0
vehicle_id          0
dtype: int64

In [6]:
customers=pd.read_sql("Select * from customers",conn)
customers

C:\Users\User\AppData\Local\Temp\ipykernel_5952\2451662662.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers=pd.read_sql("Select * from customers",conn)

    customer_id      customer_name       phone       city
0             1         Amit Patil  8608637542       Pune
1             2      Suresh Shinde  7787846414       Pune
2             3     Rahul Deshmukh  9571218620      Delhi
3             4     Priya Kulkarni  9563451924       Pune
4             5        Sneha Joshi  7670094950  Bangalore
..          ...                ...         ...        ...
95           96     Rohini Kulathe  9330861947  Bangalore
96           97  Sameer Kshirsagar  8185407468  Bangalore
97           98       Tanmay Barve  7605264936  Bangalore
98           99     Ujwala Phadnis  8272485020  Bangalore
99          100       Vivek Jadhav  7709816108  Bangalore

[100 rows x 4 columns]

In [7]:
drivers=pd.read_sql("select * from drivers",conn)
drivers

C:\Users\User\AppData\Local\Temp\ipykernel_5952\3269103672.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  drivers=pd.read_sql("select * from drivers",conn)

    driver_id          driver_name  rating    status
0           1        Santosh Pawar    4.54    active
1           2        Mahesh Shinde    3.93    active
2           3       Dilip Deshmukh    3.84    active
3           4      Ramesh Kulkarni    4.33    active
4           5         Ashok Jadhav    4.58    active
5           6           Sunil More    4.13    active
6           7        Pravin Chavan    4.97    active
7           8       Sanjay Gaikwad    4.53    active
8           9        Nitin Bhosale    4.22  inactive
9          10         Vishal Patil    4.09    active
10         11           Anand Mane    4.01    active
11         12      Bharat Salunkhe    4.59    active
12         13        Chetan Thorat    4.16    active
13         14         Dhanraj Gite    3.59    active
14         15        Eknath Kharat    4.10    active
15         16         Firoz Shaikh    4.61    active
16         17        Ganpat Kamble    3.77    active
17         18      Hanumant Pujari    3.76    active
18         19          Imran Momin    4.30    active
19         20        Jagdish Kadam    4.30    active
20         21        Kailas Gawade    4.45    active
21         22     Laxmikant Jagtap    4.77  inactive
22         23         Madhav Nikam    4.59    active
23         24      Narayan Bhujbal    4.42    active
24         25    Omprakash Gavhane    4.58    active
25         26     Pandurang Bendre    3.98    active
26         27         Qasim Pathan    4.04    active
27         28    Ravindra Patankar    3.84    active
28         29     Shankar Waghmare    3.94    active
29         30       Tukaram Ghodke    4.45    active
30         31        Umesh Shirole    3.64    active
31         32        Vilas Bhadane    4.15    active
32         33        Waseem Shaikh    4.15    active
33         34        Xavier Dsouza    4.24    active
34         35  Yogendra Kshirsagar    4.14  inactive
35         36         Zakir Shaikh    3.97    active
36         37          Ajay Phadke    4.14    active
37         38       Baban Pawaskar    4.84    active
38         39     Chandrakant More    4.92    active
39         40          Datta Barve    4.25    active
40         41          Eshwar Kale    4.44    active
41         42     Fakruddin Shaikh    3.67  inactive
42         43        Gajanan Sathe    3.98    active
43         44     Harish Karmarkar    4.12    active
44         45         Irfan Bagwan    4.80    active
45         46      Jeevan Chougule    3.88    active
46         47          Kiran Parab    4.22    active
47         48          Lalit Patne    4.98    active
48         49         Mangesh Tare    4.28    active
49         50    Nilesh Pargaonkar    4.42    active

In [8]:
payments=pd.read_sql("select * from payments",conn)
payments

C:\Users\User\AppData\Local\Temp\ipykernel_5952\332526131.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  payments=pd.read_sql("select * from payments",conn)

     payment_id  amount payment_method payment_date  ride_id payment_status
0             1  175.80            UPI   2024-01-01        1        success
1             2  447.57           Cash   2024-01-02        2        success
2             3  386.47           Card   2024-01-03        3        success
3             4  478.88           Card   2024-01-04        4        success
4             5  198.84            UPI   2024-01-05        5        success
..          ...     ...            ...          ...      ...            ...
145         146  296.59           Card   2024-05-25      133        success
146         147  240.56           Card   2024-05-26      134         failed
147         148  305.83           Cash   2024-05-27      135        success
148         149  309.17           Card   2024-05-28      136         failed
149         150  379.24            UPI   2024-05-29      137     processing

[150 rows x 6 columns]

In [9]:
vehicles=pd.read_sql("Select * from vehicles",conn)
vehicles

rides_df

C:\Users\User\AppData\Local\Temp\ipykernel_5952\241563870.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vehicles=pd.read_sql("Select * from vehicles",conn)

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,status,vehicle_id
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1
1,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2
2,3,79,40,Hinjewadi,Shivajinagar,2024-02-01 02:00:00,2024-02-01 02:20:00,121.44,completed,3
3,4,7,20,Wakad,Shivajinagar,2024-02-01 03:00:00,2024-02-01 03:20:00,310.31,completed,4
4,5,66,18,Kothrud,Wakad,2024-02-01 04:00:00,2024-02-01 04:20:00,311.30,completed,5
...,...,...,...,...,...,...,...,...,...,...
295,296,70,38,Shivajinagar,Wakad,2024-02-13 07:00:00,2024-02-13 07:20:00,321.66,completed,46
296,297,4,44,Shivajinagar,Shivajinagar,2024-02-13 08:00:00,2024-02-13 08:20:00,340.15,completed,47
297,298,64,41,Shivajinagar,Shivajinagar,2024-02-13 09:00:00,2024-02-13 09:20:00,140.73,completed,48
298,299,70,34,Baner,Hinjewadi,2024-02-13 10:00:00,2024-02-13 10:20:00,558.94,completed,49
299,300,51,6,Kothrud,Shivajinagar,2026-04-01 12:33:10,NaT,331.61,ongoing,50

In [10]:
df=rides_df.merge(customers,on="customer_id")\
.merge(drivers,on="driver_id") \
.merge(payments,on="ride_id")\
.merge(vehicles,on="vehicle_id")

In [11]:
df.head()

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,status_x,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,1,175.80,UPI,2024-01-01,success,SUV,MH12AB1000
1,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,32,325.18,UPI,2024-02-01,success,SUV,MH12AB1000
2,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2,...,Qasim Pathan,4.04,active,2,447.57,Cash,2024-01-02,success,SUV,MH12AB1001
3,3,79,40,Hinjewadi,Shivajinagar,2024-02-01 02:00:00,2024-02-01 02:20:00,121.44,completed,3,...,Datta Barve,4.25,active,3,386.47,Card,2024-01-03,success,Mini,MH12AB1002
4,4,7,20,Wakad,Shivajinagar,2024-02-01 03:00:00,2024-02-01 03:20:00,310.31,completed,4,...,Jagdish Kadam,4.30,active,4,478.88,Card,2024-01-04,success,Auto,MH12AB1003

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ride_id          150 non-null    int64
 1   customer_id      150 non-null    int64
 2   driver_id        150 non-null    int64
 3   pickup_location  150 non-null    object
 4   drop_location    150 non-null    object
 5   pickup_time      150 non-null    datetime64[ns]
 6   drop_time        137 non-null    datetime64[ns]
 7   fare             150 non-null    float64
 8   status_x         150 non-null    object
 9   vehicle_id       150 non-null    int64
 10  customer_name    150 non-null    object
 11  phone            150 non-null    object
 12  city             150 non-null    object
 13  driver_name      150 non-null    object
 14  rating           150 non-null    float64
 15  status_y         150 non-null    object
 16  payment_id       150 non-null    int64
 17  amount           150 non-null    float64
 18  payment_method   150 non-null    object
 19  payment_date     150 non-null    datetime64[ns]
 20  payment_status   150 non-null    object
 21  vehicle_type     150 non-null    object
 22  vehicle_number   150 non-null    object
dtypes: datetime64[ns](3), float64(3), int64(5), object(12)
memory usage: 27.1+ KB

In [13]:
df.shape

(150, 23)

In [14]:
df.describe()

,ride_id,customer_id,driver_id,pickup_time,drop_time,fare,vehicle_id,rating,payment_id,amount,payment_date
count,150.000000,150.000000,150.000000,150,137,150.000000,150.000000,150.000000,150.000000,150.000000,150
mean,75.586667,52.333333,25.153333,2024-03-22 08:29:59.400000,2024-02-04 03:27:00.437956608,359.068067,24.253333,4.266600,75.500000,264.070667,2024-03-15 12:00:00
min,1.000000,2.000000,1.000000,2024-02-01 00:00:00,2024-02-01 00:20:00,80.200000,1.000000,3.590000,1.000000,52.330000,2024-01-01 00:00:00
25%,36.250000,24.250000,13.250000,2024-02-02 13:15:00,2024-02-02 11:20:00,256.197500,13.000000,4.010000,38.250000,162.680000,2024-02-07 06:00:00
50%,72.500000,57.000000,24.000000,2024-02-04 03:30:00,2024-02-04 00:20:00,353.445000,23.500000,4.250000,75.500000,246.680000,2024-03-15 12:00:00
75%,107.750000,79.000000,38.000000,2024-02-05 17:45:00,2024-02-05 11:20:00,469.470000,35.750000,4.530000,112.750000,364.035000,2024-04-21 18:00:00
max,289.000000,100.000000,50.000000,2026-04-01 12:33:10,2024-02-13 00:20:00,599.310000,50.000000,4.980000,150.000000,491.830000,2024-05-29 00:00:00
std,51.008643,30.881603,14.036738,NaN,NaN,136.819066,14.034563,0.342409,43.445368,130.995666,NaN

In [15]:
df.isnull().sum()

ride_id             0
customer_id         0
driver_id           0
pickup_location     0
drop_location       0
pickup_time         0
drop_time          13
fare                0
status_x            0
vehicle_id          0
customer_name       0
phone               0
city                0
driver_name         0
rating              0
status_y            0
payment_id          0
amount              0
payment_method      0
payment_date        0
payment_status      0
vehicle_type        0
vehicle_number      0
dtype: int64

In [16]:
df.rename(columns={"status_x":"ride_status"},inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ride_id          150 non-null    int64
 1   customer_id      150 non-null    int64
 2   driver_id        150 non-null    int64
 3   pickup_location  150 non-null    object
 4   drop_location    150 non-null    object
 5   pickup_time      150 non-null    datetime64[ns]
 6   drop_time        137 non-null    datetime64[ns]
 7   fare             150 non-null    float64
 8   ride_status      150 non-null    object
 9   vehicle_id       150 non-null    int64
 10  customer_name    150 non-null    object
 11  phone            150 non-null    object
 12  city             150 non-null    object
 13  driver_name      150 non-null    object
 14  rating           150 non-null    float64
 15  status_y         150 non-null    object
 16  payment_id       150 non-null    int64
 17  amount           150 non-null    float64
 18  payment_method   150 non-null    object
 19  payment_date     150 non-null    datetime64[ns]
 20  payment_status   150 non-null    object
 21  vehicle_type     150 non-null    object
 22  vehicle_number   150 non-null    object
dtypes: datetime64[ns](3), float64(3), int64(5), object(12)
memory usage: 27.1+ KB

Basic Filtering (Single Condition)

Select all rides that were cancelled.

Find rides where the fare is greater than 500.

Display rides booked by customers from Pune.

Get all rides paid using UPI.

List drivers whose rating is less than 3.

In [18]:
data1=df[df["ride_status"]=="cancelled"]
data1

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
7,7,71,30,Kothrud,Wakad,2024-02-01 06:00:00,2024-02-01 06:20:00,260.78,cancelled,7,...,Tukaram Ghodke,4.45,active,7,307.53,Cash,2024-01-07,success,Auto,MH12AB1006
14,14,14,49,Baner,Hinjewadi,2024-02-01 13:00:00,2024-02-01 13:20:00,335.31,cancelled,14,...,Mangesh Tare,4.28,active,14,217.71,UPI,2024-01-14,success,Mini,MH12AB1013
21,21,64,43,Kothrud,Hinjewadi,2024-02-01 20:00:00,2024-02-01 20:20:00,224.41,cancelled,21,...,Gajanan Sathe,3.98,active,21,211.39,Card,2024-01-21,success,Mini,MH12AB1020
29,28,98,46,Hinjewadi,Wakad,2024-02-02 03:00:00,2024-02-02 03:20:00,304.83,cancelled,28,...,Jeevan Chougule,3.88,active,28,298.77,Card,2024-01-28,success,Sedan,MH12AB1027
36,35,36,9,Wakad,Wakad,2024-02-02 10:00:00,2024-02-02 10:20:00,271.86,cancelled,35,...,Nitin Bhosale,4.22,inactive,48,427.52,Card,2024-02-17,pending,SUV,MH12AB1034
43,42,63,14,Wakad,Wakad,2024-02-02 17:00:00,2024-02-02 17:20:00,465.52,cancelled,42,...,Dhanraj Gite,3.59,active,55,422.54,Cash,2024-02-24,success,SUV,MH12AB1041
50,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,34,52.33,Cash,2024-02-03,success,SUV,MH12AB1048
51,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,62,364.78,UPI,2024-03-02,success,SUV,MH12AB1048
58,56,58,9,Kothrud,Baner,2024-02-03 07:00:00,2024-02-03 07:20:00,530.49,cancelled,6,...,Nitin Bhosale,4.22,inactive,69,245.08,UPI,2024-03-09,success,Mini,MH12AB1005
65,63,57,48,Shivajinagar,Kothrud,2024-02-03 14:00:00,2024-02-03 14:20:00,184.44,cancelled,13,...,Lalit Patne,4.98,active,76,76.19,Cash,2024-03-16,success,Sedan,MH12AB1012
80,77,67,17,Hinjewadi,Baner,2024-02-04 04:00:00,2024-02-04 04:20:00,315.92,cancelled,27,...,Ganpat Kamble,3.77,active,90,121.39,Card,2024-03-30,processing,Sedan,MH12AB1026
87,84,56,16,Wakad,Wakad,2024-02-04 11:00:00,2024-02-04 11:20:00,313.73,cancelled,34,...,Firoz Shaikh,4.61,active,97,128.90,Card,2024-04-06,success,Mini,MH12AB1033
94,91,18,13,Baner,Hinjewadi,2024-02-04 18:00:00,2024-02-04 18:20:00,244.33,cancelled,41,...,Chetan Thorat,4.16,active,104,71.63,UPI,2024-04-13,success,Sedan,MH12AB1040
102,98,26,16,Hinjewadi,Kothrud,2024-02-05 01:00:00,2024-02-05 01:20:00,209.14,cancelled,48,...,Firoz Shaikh,4.61,active,111,292.72,Card,2024-04-20,success,Mini,MH12AB1047
116,112,41,9,Baner,Shivajinagar,2024-02-05 15:00:00,2024-02-05 15:20:00,153.66,cancelled,12,...,Nitin Bhosale,4.22,inactive,125,419.19,Cash,2024-05-04,success,Sedan,MH12AB1011
123,119,45,47,Wakad,Wakad,2024-02-05 22:00:00,2024-02-05 22:20:00,307.22,cancelled,19,...,Kiran Parab,4.22,active,132,328.21,Card,2024-05-11,pending,Sedan,MH12AB1018
131,126,79,38,Kothrud,Shivajinagar,2024-02-06 05:00:00,2024-02-06 05:20:00,294.31,cancelled,26,...,Baban Pawaskar,4.84,active,139,273.22,UPI,2024-05-18,failed,SUV,MH12AB1025
138,133,50,3,Wakad,Shivajinagar,2024-02-06 12:00:00,2024-02-06 12:20:00,433.49,cancelled,33,...,Dilip Deshmukh,3.84,active,146,296.59,Card,2024-05-25,success,Mini,MH12AB1032
146,217,52,20,Baner,Kothrud,2024-02-10 00:00:00,2024-02-10 00:20:00,203.53,cancelled,17,...,Jagdish Kadam,4.30,active,41,62.43,Card,2024-02-10,success,Auto,MH12AB1016

In [19]:
data2=df[df["fare"]>500]
data2

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
2,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2,...,Qasim Pathan,4.04,active,2,447.57,Cash,2024-01-02,success,SUV,MH12AB1001
6,6,95,20,Wakad,Kothrud,2024-02-01 05:00:00,2024-02-01 05:20:00,526.11,completed,6,...,Jagdish Kadam,4.30,active,6,298.74,Cash,2024-01-06,success,Mini,MH12AB1005
8,8,41,10,Hinjewadi,Wakad,2024-02-01 07:00:00,2024-02-01 07:20:00,547.96,completed,8,...,Vishal Patil,4.09,active,8,491.15,Card,2024-01-08,success,Sedan,MH12AB1007
12,12,26,50,Hinjewadi,Hinjewadi,2024-02-01 11:00:00,2024-02-01 11:20:00,505.36,completed,12,...,Nilesh Pargaonkar,4.42,active,12,170.81,Card,2024-01-12,pending,Sedan,MH12AB1011
15,15,45,19,Baner,Shivajinagar,2026-04-01 12:33:10,2024-02-01 14:20:00,551.78,booked,15,...,Imran Momin,4.30,active,15,227.61,Cash,2024-01-15,processing,SUV,MH12AB1014
19,19,57,42,Hinjewadi,Wakad,2024-02-01 18:00:00,2024-02-01 18:20:00,570.79,completed,19,...,Fakruddin Shaikh,3.67,inactive,19,144.01,UPI,2024-01-19,success,Sedan,MH12AB1018
34,33,46,16,Shivajinagar,Baner,2024-02-02 08:00:00,2024-02-02 08:20:00,592.24,completed,33,...,Firoz Shaikh,4.61,active,46,119.77,UPI,2024-02-15,success,Mini,MH12AB1032
35,34,58,40,Baner,Baner,2024-02-02 09:00:00,2024-02-02 09:20:00,596.04,completed,34,...,Datta Barve,4.25,active,47,491.83,UPI,2024-02-16,success,Mini,MH12AB1033
40,39,55,4,Shivajinagar,Shivajinagar,2024-02-02 14:00:00,2024-02-02 14:20:00,508.93,completed,39,...,Ramesh Kulkarni,4.33,active,52,186.47,Cash,2024-02-21,success,Sedan,MH12AB1038
41,40,74,40,Hinjewadi,Shivajinagar,2024-02-02 15:00:00,NaT,558.19,ongoing,40,...,Datta Barve,4.25,active,53,291.69,Card,2024-02-22,success,Auto,MH12AB1039
46,45,27,30,Wakad,Kothrud,2026-04-01 12:33:10,2024-02-02 20:20:00,518.70,booked,45,...,Tukaram Ghodke,4.45,active,58,255.77,UPI,2024-02-27,success,Auto,MH12AB1044
58,56,58,9,Kothrud,Baner,2024-02-03 07:00:00,2024-02-03 07:20:00,530.49,cancelled,6,...,Nitin Bhosale,4.22,inactive,69,245.08,UPI,2024-03-09,success,Mini,MH12AB1005
67,65,88,25,Baner,Hinjewadi,2024-02-03 16:00:00,2024-02-03 16:20:00,539.65,completed,15,...,Omprakash Gavhane,4.58,active,78,249.06,UPI,2024-03-18,success,SUV,MH12AB1014
68,66,5,20,Kothrud,Hinjewadi,2024-02-03 17:00:00,2024-02-03 17:20:00,501.08,completed,16,...,Jagdish Kadam,4.30,active,79,157.90,Card,2024-03-19,success,Sedan,MH12AB1015
75,73,70,30,Shivajinagar,Wakad,2024-02-04 00:00:00,2024-02-04 00:20:00,521.46,completed,23,...,Tukaram Ghodke,4.45,active,35,332.55,Cash,2024-02-04,success,Auto,MH12AB1022
76,73,70,30,Shivajinagar,Wakad,2024-02-04 00:00:00,2024-02-04 00:20:00,521.46,completed,23,...,Tukaram Ghodke,4.45,active,86,246.05,Cash,2024-03-26,success,Auto,MH12AB1022
77,74,10,11,Kothrud,Baner,2024-02-04 01:00:00,2024-02-04 01:20:00,510.74,completed,24,...,Anand Mane,4.01,active,87,378.52,Cash,2024-03-27,success,Mini,MH12AB1023
82,79,4,47,Baner,Kothrud,2024-02-04 06:00:00,2024-02-04 06:20:00,590.63,completed,29,...,Kiran Parab,4.22,active,92,203.85,UPI,2024-04-01,success,Mini,MH12AB1028
85,82,24,43,Hinjewadi,Kothrud,2024-02-04 09:00:00,2024-02-04 09:20:00,571.88,completed,32,...,Gajanan Sathe,3.98,active,95,190.14,UPI,2024-04-04,success,Auto,MH12AB1031
99,96,9,42,Baner,Baner,2024-02-04 23:00:00,2024-02-04 23:20:00,529.98,completed,46,...,Fakruddin Shaikh,3.67,inactive,109,470.05,Card,2024-04-18,failed,Auto,MH12AB1045
111,107,83,15,Baner,Kothrud,2024-02-05 10:00:00,2024-02-05 10:20:00,599.31,completed,7,...,Eknath Kharat,4.10,active,120,308.02,Cash,2024-04-29,processing,Auto,MH12AB1006
118,114,88,13,Kothrud,Kothrud,2024-02-05 17:00:00,2024-02-05 17:20:00,594.70,completed,14,...,Chetan Thorat,4.16,active,127,143.01,Cash,2024-05-06,success,Mini,MH12AB1013
124,120,93,31,Shivajinagar,Shivajinagar,2026-04-01 12:33:10,NaT,522.41,ongoing,20,...,Umesh Shirole,3.64,active,133,201.45,Card,2024-05-12,success,Mini,MH12AB1019
128,123,82,16,Wakad,Wakad,2024-02-06 02:00:00,2024-02-06 02:20:00,528.07,completed,23,...,Firoz Shaikh,4.61,active,136,356.73,Card,2024-05-15,success,Auto,MH12AB1022
129,124,62,27,Baner,Kothrud,2024-02-06 03:00:00,2024-02-06 03:20:00,507.19,completed,24,...,Qasim Pathan,4.04,active,137,203.28,Cash,2024-05-16,success,Mini,MH12AB1023
132,127,24,14,Hinjewadi,Shivajinagar,2024-02-06 06:00:00,2024-02-06 06:20:00,536.44,completed,27,...,Dhanraj Gite,3.59,active,140,361.80,Card,2024-05-19,refunded,Sedan,MH12AB1026
135,130,81,7,Shivajinagar,Kothrud,2024-02-06 09:00:00,NaT,594.79,ongoing,30,...,Pravin Chavan,4.97,active,143,67.63,Cash,2024-05-22,success,SUV,MH12AB1029
137,132,16,28,Baner,Hinjewadi,2024-02-06 11:00:00,2024-02-06 11:20:00,561.13,completed,32,...,Ravindra Patankar,3.84,active,145,485.41,UPI,2024-05-24,success,Auto,MH12AB1031
141,136,91,29,Baner,Baner,2024-02-06 15:00:00,2024-02-06 15:20:00,513.68,completed,36,...,Shankar Waghmare,3.94,active,149,309.17,Card,2024-05-28,failed,Auto,MH12AB1035
149,289,3,38,Shivajinagar,Kothrud,2024-02-13 00:00:00,2024-02-13 00:20:00,527.94,completed,39,...,Baban Pawaskar,4.84,active,44,352.41,Cash,2024-02-13,success,Sedan,MH12AB1038

In [20]:
data3=df[df["city"]=="Pune"]
data3

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
10,10,77,47,Hinjewadi,Shivajinagar,2024-02-01 09:00:00,NaT,203.52,ongoing,10,...,Kiran Parab,4.22,active,10,187.56,Card,2024-01-10,success,SUV,MH12AB1009
11,11,77,3,Baner,Kothrud,2024-02-01 10:00:00,2024-02-01 10:20:00,218.71,completed,11,...,Dilip Deshmukh,3.84,active,11,135.91,Cash,2024-01-11,success,Sedan,MH12AB1010
12,12,26,50,Hinjewadi,Hinjewadi,2024-02-01 11:00:00,2024-02-01 11:20:00,505.36,completed,12,...,Nilesh Pargaonkar,4.42,active,12,170.81,Card,2024-01-12,pending,Sedan,MH12AB1011
15,15,45,19,Baner,Shivajinagar,2026-04-01 12:33:10,2024-02-01 14:20:00,551.78,booked,15,...,Imran Momin,4.30,active,15,227.61,Cash,2024-01-15,processing,SUV,MH12AB1014
16,16,2,36,Hinjewadi,Kothrud,2024-02-01 15:00:00,2024-02-01 15:20:00,162.90,completed,16,...,Zakir Shaikh,3.97,active,16,429.90,Cash,2024-01-16,success,Sedan,MH12AB1015
19,19,57,42,Hinjewadi,Wakad,2024-02-01 18:00:00,2024-02-01 18:20:00,570.79,completed,19,...,Fakruddin Shaikh,3.67,inactive,19,144.01,UPI,2024-01-19,success,Sedan,MH12AB1018
23,23,4,42,Shivajinagar,Baner,2024-02-01 22:00:00,2024-02-01 22:20:00,499.86,completed,23,...,Fakruddin Shaikh,3.67,inactive,23,182.88,Cash,2024-01-23,success,Auto,MH12AB1022
28,27,70,21,Baner,Baner,2024-02-02 02:00:00,2024-02-02 02:20:00,411.11,completed,27,...,Kailas Gawade,4.45,active,27,369.01,Cash,2024-01-27,success,Sedan,MH12AB1026
32,31,19,47,Baner,Wakad,2024-02-02 06:00:00,2024-02-02 06:20:00,253.58,completed,31,...,Kiran Parab,4.22,active,31,165.29,Card,2024-01-31,success,Auto,MH12AB1030
36,35,36,9,Wakad,Wakad,2024-02-02 10:00:00,2024-02-02 10:20:00,271.86,cancelled,35,...,Nitin Bhosale,4.22,inactive,48,427.52,Card,2024-02-17,pending,SUV,MH12AB1034
37,36,19,27,Wakad,Kothrud,2024-02-02 11:00:00,2024-02-02 11:20:00,224.64,completed,36,...,Qasim Pathan,4.04,active,49,437.18,UPI,2024-02-18,success,Auto,MH12AB1035
41,40,74,40,Hinjewadi,Shivajinagar,2024-02-02 15:00:00,NaT,558.19,ongoing,40,...,Datta Barve,4.25,active,53,291.69,Card,2024-02-22,success,Auto,MH12AB1039
42,41,82,1,Kothrud,Kothrud,2024-02-02 16:00:00,2024-02-02 16:20:00,446.28,completed,41,...,Santosh Pawar,4.54,active,54,196.99,Card,2024-02-23,success,Sedan,MH12AB1040
43,42,63,14,Wakad,Wakad,2024-02-02 17:00:00,2024-02-02 17:20:00,465.52,cancelled,42,...,Dhanraj Gite,3.59,active,55,422.54,Cash,2024-02-24,success,SUV,MH12AB1041
44,43,68,8,Shivajinagar,Shivajinagar,2024-02-02 18:00:00,2024-02-02 18:20:00,294.70,completed,43,...,Sanjay Gaikwad,4.53,active,56,172.19,Card,2024-02-25,success,Sedan,MH12AB1042
47,46,93,25,Baner,Shivajinagar,2024-02-02 21:00:00,2024-02-02 21:20:00,363.54,completed,46,...,Omprakash Gavhane,4.58,active,59,428.91,Card,2024-02-28,success,Auto,MH12AB1045
50,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,34,52.33,Cash,2024-02-03,success,SUV,MH12AB1048
51,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,62,364.78,UPI,2024-03-02,success,SUV,MH12AB1048
56,54,26,10,Baner,Wakad,2024-02-03 05:00:00,2024-02-03 05:20:00,446.36,completed,4,...,Vishal Patil,4.09,active,67,68.48,UPI,2024-03-07,failed,Auto,MH12AB1003
59,57,4,1,Baner,Wakad,2024-02-03 08:00:00,2024-02-03 08:20:00,299.90,completed,7,...,Santosh Pawar,4.54,active,70,384.82,Cash,2024-03-10,success,Auto,MH12AB1006
64,62,49,19,Hinjewadi,Wakad,2024-02-03 13:00:00,2024-02-03 13:20:00,275.51,completed,12,...,Imran Momin,4.30,active,75,359.82,Cash,2024-03-15,processing,Sedan,MH12AB1011
65,63,57,48,Shivajinagar,Kothrud,2024-02-03 14:00:00,2024-02-03 14:20:00,184.44,cancelled,13,...,Lalit Patne,4.98,active,76,76.19,Cash,2024-03-16,success,Sedan,MH12AB1012
69,67,70,26,Hinjewadi,Kothrud,2024-02-03 18:00:00,2024-02-03 18:20:00,375.64,completed,17,...,Pandurang Bendre,3.98,active,80,92.24,Cash,2024-03-20,refunded,Auto,MH12AB1016
70,68,57,7,Baner,Wakad,2024-02-03 19:00:00,2024-02-03 19:20:00,459.38,completed,18,...,Pravin Chavan,4.97,active,81,132.29,Cash,2024-03-21,success,Sedan,MH12AB1017
75,73,70,30,Shivajinagar,Wakad,2024-02-04 00:00:00,2024-02-04 00:20:00,521.46,completed,23,...,Tukaram Ghodke,4.45,active,35,332.55,Cash,2024-02-04,success,Auto,MH12AB1022
76,73,70,30,Shivajinagar,Wakad,2024-02-04 00:00:00,2024-02-04 00:20:00,521.46,completed,23,...,Tukaram Ghodke,4.45,active,86,246.05,Cash,2024-03-26,success,Auto,MH12AB1022
78,75,80,8,Hinjewadi,Hinjewadi,2026-04-01 12:33:10,2024-02-04 02:20:00,284.82,booked,25,...,Sanjay Gaikwad,4.53,active,88,71.47,UPI,2024-03-28,success,Sedan,MH12AB1024
82,79,4,47,Baner,Kothrud,2024-02-04 06:00:00,2024-02-04 06:20:00,590.63,completed,29,...,Kiran Parab,4.22,active,92,203.85,UPI,2024-04-01,success,Mini,MH12AB1028
83,80,49,44,Shivajinagar,Shivajinagar,2024-02-04 07:00:00,NaT,121.68,ongoing,30,...,Harish Karmarkar,4.12,active,93,91.31,Card,2024-04-02,success,SUV,MH12AB1029
84,81,4,30,Baner,Hinjewadi,2024-02-04 08:00:00,2024-02-04 08:20:00,301.18,completed,31,...,Tukaram Ghodke,4.45,active,94,92.37,Card,2024-04-03,success,Auto,MH12AB1030
90,87,50,50,Hinjewadi,Kothrud,2024-02-04 14:00:00,2024-02-04 14:20:00,389.59,completed,37,...,Nilesh Pargaonkar,4.42,active,100,413.11,Card,2024-04-09,refunded,Auto,MH12AB1036
93,90,26,35,Shivajinagar,Baner,2026-04-01 12:33:10,NaT,292.92,ongoing,40,...,Yogendra Kshirsagar,4.14,inactive,103,342.40,UPI,2024-04-12,success,Auto,MH12AB1039
102,98,26,16,Hinjewadi,Kothrud,2024-02-05 01:00:00,2024-02-05 01:20:00,209.14,cancelled,48,...,Firoz Shaikh,4.61,active,111,292.72,Card,2024-04-20,success,Mini,MH12AB1047
104,100,68,46,Shivajinagar,Wakad,2024-02-05 03:00:00,NaT,338.73,ongoing,50,...,Jeevan Chougule,3.88,active,113,327.13,UPI,2024-04-22,success,Mini,MH12AB1049
112,108,93,21,Kothrud,Baner,2024-02-05 11:00:00,2024-02-05 11:20:00,92.04,completed,8,...,Kailas Gawade,4.45,active,121,107.83,UPI,2024-04-30,failed,Sedan,MH12AB1007
114,110,6,22,Kothrud,Hinjewadi,2024-02-05 13:00:00,NaT,323.12,ongoing,10,...,Laxmikant Jagtap,4.77,inactive,123,419.29,Cash,2024-05-02,success,SUV,MH12AB1009
123,119,45,47,Wakad,Wakad,2024-02-05 22:00:00,2024-02-05 22:20:00,307.22,cancelled,19,...,Kiran Parab,4.22,active,132,328.21,Card,2024-05-11,pending,Sedan,MH12AB1018
124,120,93,31,Shivajinagar,Shivajinagar,2026-04-01 12:33:10,NaT,522.41,ongoing,20,...,Umesh Shirole,3.64,active,133,201.45,Card,2024-05-12,success,Mini,MH12AB1019
128,123,82,16,Wakad,Wakad,2024-02-06 02:00:00,2024-02-06 02:20:00,528.07,completed,23,...,Firoz Shaikh,4.61,active,136,356.73,Card,2024-05-15,success,Auto,MH12AB1022
133,128,63,37,Baner,Kothrud,2024-02-06 07:00:00,2024-02-06 07:20:00,352.91,completed,28,...,Ajay Phadke,4.14,active,141,206.75,Card,2024-05-20,success,Sedan,MH12AB1027
138,133,50,3,Wakad,Shivajinagar,2024-02-06 12:00:00,2024-02-06 12:20:00,433.49,cancelled,33,...,Dilip Deshmukh,3.84,active,146,296.59,Card,2024-05-25,success,Mini,MH12AB1032
141,136,91,29,Baner,Baner,2024-02-06 15:00:00,2024-02-06 15:20:00,513.68,completed,36,...,Shankar Waghmare,3.94,active,149,309.17,Card,2024-05-28,failed,Auto,MH12AB1035
143,145,36,39,Kothrud,Baner,2024-02-07 00:00:00,2024-02-07 00:20:00,409.46,completed,45,...,Chandrakant More,4.92,active,38,228.55,Card,2024-02-07,success,Auto,MH12AB1044
144,169,6,17,Baner,Shivajinagar,2024-02-08 00:00:00,2024-02-08 00:20:00,428.86,completed,19,...,Ganpat Kamble,3.77,active,39,72.85,Cash,2024-02-08,success,Sedan,MH12AB1018
147,241,80,24,Wakad,Baner,2024-02-11 00:00:00,2024-02-11 00:20:00,487.62,completed,41,...,Narayan Bhujbal,4.42,active,42,310.49,Cash,2024-02-11,success,Sedan,MH12AB1040

In [21]:
data4=df[df["payment_method"]=="UPI"]
data4

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,1,175.80,UPI,2024-01-01,success,SUV,MH12AB1000
1,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,32,325.18,UPI,2024-02-01,success,SUV,MH12AB1000
5,5,66,18,Kothrud,Wakad,2024-02-01 04:00:00,2024-02-01 04:20:00,311.30,completed,5,...,Hanumant Pujari,3.76,active,5,198.84,UPI,2024-01-05,success,SUV,MH12AB1004
14,14,14,49,Baner,Hinjewadi,2024-02-01 13:00:00,2024-02-01 13:20:00,335.31,cancelled,14,...,Mangesh Tare,4.28,active,14,217.71,UPI,2024-01-14,success,Mini,MH12AB1013
17,17,42,40,Baner,Baner,2024-02-01 16:00:00,2024-02-01 16:20:00,341.05,completed,17,...,Datta Barve,4.25,active,17,468.51,UPI,2024-01-17,success,Auto,MH12AB1016
19,19,57,42,Hinjewadi,Wakad,2024-02-01 18:00:00,2024-02-01 18:20:00,570.79,completed,19,...,Fakruddin Shaikh,3.67,inactive,19,144.01,UPI,2024-01-19,success,Sedan,MH12AB1018
30,29,51,13,Shivajinagar,Hinjewadi,2024-02-02 04:00:00,2024-02-02 04:20:00,280.38,completed,29,...,Chetan Thorat,4.16,active,29,183.43,UPI,2024-01-29,failed,Mini,MH12AB1028
34,33,46,16,Shivajinagar,Baner,2024-02-02 08:00:00,2024-02-02 08:20:00,592.24,completed,33,...,Firoz Shaikh,4.61,active,46,119.77,UPI,2024-02-15,success,Mini,MH12AB1032
35,34,58,40,Baner,Baner,2024-02-02 09:00:00,2024-02-02 09:20:00,596.04,completed,34,...,Datta Barve,4.25,active,47,491.83,UPI,2024-02-16,success,Mini,MH12AB1033
37,36,19,27,Wakad,Kothrud,2024-02-02 11:00:00,2024-02-02 11:20:00,224.64,completed,36,...,Qasim Pathan,4.04,active,49,437.18,UPI,2024-02-18,success,Auto,MH12AB1035
39,38,47,3,Kothrud,Wakad,2024-02-02 13:00:00,2024-02-02 13:20:00,243.42,completed,38,...,Dilip Deshmukh,3.84,active,51,67.48,UPI,2024-02-20,success,Auto,MH12AB1037
46,45,27,30,Wakad,Kothrud,2026-04-01 12:33:10,2024-02-02 20:20:00,518.70,booked,45,...,Tukaram Ghodke,4.45,active,58,255.77,UPI,2024-02-27,success,Auto,MH12AB1044
49,48,11,16,Hinjewadi,Hinjewadi,2024-02-02 23:00:00,2024-02-02 23:20:00,421.39,completed,48,...,Firoz Shaikh,4.61,active,61,235.11,UPI,2024-03-01,success,Mini,MH12AB1047
51,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,62,364.78,UPI,2024-03-02,success,SUV,MH12AB1048
54,52,60,48,Kothrud,Wakad,2024-02-03 03:00:00,2024-02-03 03:20:00,183.14,completed,2,...,Lalit Patne,4.98,active,65,486.29,UPI,2024-03-05,success,SUV,MH12AB1001
56,54,26,10,Baner,Wakad,2024-02-03 05:00:00,2024-02-03 05:20:00,446.36,completed,4,...,Vishal Patil,4.09,active,67,68.48,UPI,2024-03-07,failed,Auto,MH12AB1003
58,56,58,9,Kothrud,Baner,2024-02-03 07:00:00,2024-02-03 07:20:00,530.49,cancelled,6,...,Nitin Bhosale,4.22,inactive,69,245.08,UPI,2024-03-09,success,Mini,MH12AB1005
60,58,100,34,Kothrud,Shivajinagar,2024-02-03 09:00:00,2024-02-03 09:20:00,328.19,completed,8,...,Xavier Dsouza,4.24,active,71,162.89,UPI,2024-03-11,success,Sedan,MH12AB1007
62,60,86,21,Kothrud,Baner,2026-04-01 12:33:10,NaT,118.36,ongoing,10,...,Kailas Gawade,4.45,active,73,86.39,UPI,2024-03-13,success,SUV,MH12AB1009
63,61,60,24,Baner,Baner,2024-02-03 12:00:00,2024-02-03 12:20:00,224.47,completed,11,...,Narayan Bhujbal,4.42,active,74,242.74,UPI,2024-03-14,success,Sedan,MH12AB1010
67,65,88,25,Baner,Hinjewadi,2024-02-03 16:00:00,2024-02-03 16:20:00,539.65,completed,15,...,Omprakash Gavhane,4.58,active,78,249.06,UPI,2024-03-18,success,SUV,MH12AB1014
71,69,61,3,Shivajinagar,Hinjewadi,2024-02-03 20:00:00,2024-02-03 20:20:00,334.29,completed,19,...,Dilip Deshmukh,3.84,active,82,470.58,UPI,2024-03-22,failed,Sedan,MH12AB1018
78,75,80,8,Hinjewadi,Hinjewadi,2026-04-01 12:33:10,2024-02-04 02:20:00,284.82,booked,25,...,Sanjay Gaikwad,4.53,active,88,71.47,UPI,2024-03-28,success,Sedan,MH12AB1024
82,79,4,47,Baner,Kothrud,2024-02-04 06:00:00,2024-02-04 06:20:00,590.63,completed,29,...,Kiran Parab,4.22,active,92,203.85,UPI,2024-04-01,success,Mini,MH12AB1028
85,82,24,43,Hinjewadi,Kothrud,2024-02-04 09:00:00,2024-02-04 09:20:00,571.88,completed,32,...,Gajanan Sathe,3.98,active,95,190.14,UPI,2024-04-04,success,Auto,MH12AB1031
86,83,92,43,Hinjewadi,Kothrud,2024-02-04 10:00:00,2024-02-04 10:20:00,454.86,completed,33,...,Gajanan Sathe,3.98,active,96,490.78,UPI,2024-04-05,pending,Mini,MH12AB1032
89,86,38,21,Shivajinagar,Hinjewadi,2024-02-04 13:00:00,2024-02-04 13:20:00,80.20,completed,36,...,Kailas Gawade,4.45,active,99,393.51,UPI,2024-04-08,success,Auto,MH12AB1035
93,90,26,35,Shivajinagar,Baner,2026-04-01 12:33:10,NaT,292.92,ongoing,40,...,Yogendra Kshirsagar,4.14,inactive,103,342.40,UPI,2024-04-12,success,Auto,MH12AB1039
94,91,18,13,Baner,Hinjewadi,2024-02-04 18:00:00,2024-02-04 18:20:00,244.33,cancelled,41,...,Chetan Thorat,4.16,active,104,71.63,UPI,2024-04-13,success,Sedan,MH12AB1040
95,92,59,43,Kothrud,Shivajinagar,2024-02-04 19:00:00,2024-02-04 19:20:00,445.22,completed,42,...,Gajanan Sathe,3.98,active,105,477.12,UPI,2024-04-14,processing,SUV,MH12AB1041
104,100,68,46,Shivajinagar,Wakad,2024-02-05 03:00:00,NaT,338.73,ongoing,50,...,Jeevan Chougule,3.88,active,113,327.13,UPI,2024-04-22,success,Mini,MH12AB1049
110,106,40,10,Hinjewadi,Shivajinagar,2024-02-05 09:00:00,2024-02-05 09:20:00,218.96,completed,6,...,Vishal Patil,4.09,active,119,354.73,UPI,2024-04-28,success,Mini,MH12AB1005
112,108,93,21,Kothrud,Baner,2024-02-05 11:00:00,2024-02-05 11:20:00,92.04,completed,8,...,Kailas Gawade,4.45,active,121,107.83,UPI,2024-04-30,failed,Sedan,MH12AB1007
113,109,39,34,Shivajinagar,Shivajinagar,2024-02-05 12:00:00,2024-02-05 12:20:00,345.42,completed,9,...,Xavier Dsouza,4.24,active,122,415.04,UPI,2024-05-01,success,Mini,MH12AB1008
119,115,22,18,Hinjewadi,Wakad,2024-02-05 18:00:00,2024-02-05 18:20:00,489.35,completed,15,...,Hanumant Pujari,3.76,active,128,173.28,UPI,2024-05-07,success,SUV,MH12AB1014
127,122,84,23,Baner,Baner,2024-02-06 01:00:00,2024-02-06 01:20:00,344.56,completed,22,...,Madhav Nikam,4.59,active,135,223.43,UPI,2024-05-14,processing,SUV,MH12AB1021
131,126,79,38,Kothrud,Shivajinagar,2024-02-06 05:00:00,2024-02-06 05:20:00,294.31,cancelled,26,...,Baban Pawaskar,4.84,active,139,273.22,UPI,2024-05-18,failed,SUV,MH12AB1025
136,131,25,12,Wakad,Shivajinagar,2024-02-06 10:00:00,2024-02-06 10:20:00,196.77,completed,31,...,Bharat Salunkhe,4.59,active,144,238.08,UPI,2024-05-23,pending,Auto,MH12AB1030
137,132,16,28,Baner,Hinjewadi,2024-02-06 11:00:00,2024-02-06 11:20:00,561.13,completed,32,...,Ravindra Patankar,3.84,active,145,485.41,UPI,2024-05-24,success,Auto,MH12AB1031
142,137,5,20,Baner,Shivajinagar,2024-02-06 16:00:00,2024-02-06 16:20:00,180.59,completed,37,...,Jagdish Kadam,4.30,active,150,379.24,UPI,2024-05-29,processing,Auto,MH12AB1036

In [22]:
data5=df[df["rating"]<3]
data5

Empty DataFrame
Columns: [ride_id, customer_id, driver_id, pickup_location, drop_location, pickup_time, drop_time, fare, ride_status, vehicle_id, customer_name, phone, city, driver_name, rating, status_y, payment_id, amount, payment_method, payment_date, payment_status, vehicle_type, vehicle_number]
Index: []

[0 rows x 23 columns]

Two-Condition Filtering (AND)

Find rides where status is completed and fare > 300.

Select customers from Mumbai who paid using Cash.a

Get rides where driver rating > 4 and vehicle_type is SUV.

Display rides that started in Pune and ended in Mumbai.

List rides where fare > 200 and payment_status is success.

In [23]:
data6=df[(df["ride_status"]=="completed") & (df["fare"]>300)]
data6

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,1,175.80,UPI,2024-01-01,success,SUV,MH12AB1000
1,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,32,325.18,UPI,2024-02-01,success,SUV,MH12AB1000
2,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2,...,Qasim Pathan,4.04,active,2,447.57,Cash,2024-01-02,success,SUV,MH12AB1001
4,4,7,20,Wakad,Shivajinagar,2024-02-01 03:00:00,2024-02-01 03:20:00,310.31,completed,4,...,Jagdish Kadam,4.30,active,4,478.88,Card,2024-01-04,success,Auto,MH12AB1003
5,5,66,18,Kothrud,Wakad,2024-02-01 04:00:00,2024-02-01 04:20:00,311.30,completed,5,...,Hanumant Pujari,3.76,active,5,198.84,UPI,2024-01-05,success,SUV,MH12AB1004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,169,6,17,Baner,Shivajinagar,2024-02-08 00:00:00,2024-02-08 00:20:00,428.86,completed,19,...,Ganpat Kamble,3.77,active,39,72.85,Cash,2024-02-08,success,Sedan,MH12AB1018
145,193,8,7,Wakad,Wakad,2024-02-09 00:00:00,2024-02-09 00:20:00,431.31,completed,43,...,Pravin Chavan,4.97,active,40,448.98,Cash,2024-02-09,refunded,Sedan,MH12AB1042
147,241,80,24,Wakad,Baner,2024-02-11 00:00:00,2024-02-11 00:20:00,487.62,completed,41,...,Narayan Bhujbal,4.42,active,42,310.49,Cash,2024-02-11,success,Sedan,MH12AB1040
148,265,21,28,Kothrud,Hinjewadi,2024-02-12 00:00:00,2024-02-12 00:20:00,423.17,completed,15,...,Ravindra Patankar,3.84,active,43,247.31,Card,2024-02-12,success,SUV,MH12AB1014
149,289,3,38,Shivajinagar,Kothrud,2024-02-13 00:00:00,2024-02-13 00:20:00,527.94,completed,39,...,Baban Pawaskar,4.84,active,44,352.41,Cash,2024-02-13,success,Sedan,MH12AB1038

In [24]:
data7=df[(df["city"]=="Mumbai") & (df["ride_status"]=="Cash")]
data7

Empty DataFrame
Columns: [ride_id, customer_id, driver_id, pickup_location, drop_location, pickup_time, drop_time, fare, ride_status, vehicle_id, customer_name, phone, city, driver_name, rating, status_y, payment_id, amount, payment_method, payment_date, payment_status, vehicle_type, vehicle_number]
Index: []

[0 rows x 23 columns]

In [25]:
data8=df[(df["rating"]>4) & (df["vehicle_type"]=="SUV")]
data8

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
2,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2,...,Qasim Pathan,4.04,active,2,447.57,Cash,2024-01-02,success,SUV,MH12AB1001
10,10,77,47,Hinjewadi,Shivajinagar,2024-02-01 09:00:00,NaT,203.52,ongoing,10,...,Kiran Parab,4.22,active,10,187.56,Card,2024-01-10,success,SUV,MH12AB1009
15,15,45,19,Baner,Shivajinagar,2026-04-01 12:33:10,2024-02-01 14:20:00,551.78,booked,15,...,Imran Momin,4.30,active,15,227.61,Cash,2024-01-15,processing,SUV,MH12AB1014
22,22,98,8,Baner,Shivajinagar,2024-02-01 21:00:00,2024-02-01 21:20:00,101.22,completed,22,...,Sanjay Gaikwad,4.53,active,22,164.37,Card,2024-01-22,success,SUV,MH12AB1021
31,30,3,27,Baner,Hinjewadi,2026-04-01 12:33:10,NaT,427.20,ongoing,30,...,Qasim Pathan,4.04,active,30,238.90,Card,2024-01-30,processing,SUV,MH12AB1029
36,35,36,9,Wakad,Wakad,2024-02-02 10:00:00,2024-02-02 10:20:00,271.86,cancelled,35,...,Nitin Bhosale,4.22,inactive,48,427.52,Card,2024-02-17,pending,SUV,MH12AB1034
45,44,12,7,Hinjewadi,Wakad,2024-02-02 19:00:00,2024-02-02 19:20:00,116.45,completed,44,...,Pravin Chavan,4.97,active,57,484.36,Card,2024-02-26,success,SUV,MH12AB1043
48,47,76,39,Baner,Shivajinagar,2024-02-02 22:00:00,2024-02-02 22:20:00,403.40,completed,47,...,Chandrakant More,4.92,active,60,137.47,Cash,2024-02-29,processing,SUV,MH12AB1046
50,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,34,52.33,Cash,2024-02-03,success,SUV,MH12AB1048
51,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,62,364.78,UPI,2024-03-02,success,SUV,MH12AB1048
53,51,59,33,Hinjewadi,Kothrud,2024-02-03 02:00:00,2024-02-03 02:20:00,195.19,completed,1,...,Waseem Shaikh,4.15,active,64,109.74,Cash,2024-03-04,success,SUV,MH12AB1000
54,52,60,48,Kothrud,Wakad,2024-02-03 03:00:00,2024-02-03 03:20:00,183.14,completed,2,...,Lalit Patne,4.98,active,65,486.29,UPI,2024-03-05,success,SUV,MH12AB1001
57,55,28,50,Wakad,Kothrud,2024-02-03 06:00:00,2024-02-03 06:20:00,497.79,completed,5,...,Nilesh Pargaonkar,4.42,active,68,229.47,Cash,2024-03-08,success,SUV,MH12AB1004
62,60,86,21,Kothrud,Baner,2026-04-01 12:33:10,NaT,118.36,ongoing,10,...,Kailas Gawade,4.45,active,73,86.39,UPI,2024-03-13,success,SUV,MH12AB1009
67,65,88,25,Baner,Hinjewadi,2024-02-03 16:00:00,2024-02-03 16:20:00,539.65,completed,15,...,Omprakash Gavhane,4.58,active,78,249.06,UPI,2024-03-18,success,SUV,MH12AB1014
74,72,34,8,Shivajinagar,Baner,2024-02-03 23:00:00,2024-02-03 23:20:00,495.06,completed,22,...,Sanjay Gaikwad,4.53,active,85,345.70,Card,2024-03-25,success,SUV,MH12AB1021
79,76,29,37,Kothrud,Kothrud,2024-02-04 03:00:00,2024-02-04 03:20:00,487.68,completed,26,...,Ajay Phadke,4.14,active,89,304.72,Card,2024-03-29,success,SUV,MH12AB1025
83,80,49,44,Shivajinagar,Shivajinagar,2024-02-04 07:00:00,NaT,121.68,ongoing,30,...,Harish Karmarkar,4.12,active,93,91.31,Card,2024-04-02,success,SUV,MH12AB1029
88,85,35,4,Shivajinagar,Baner,2024-02-04 12:00:00,2024-02-04 12:20:00,224.02,completed,35,...,Ramesh Kulkarni,4.33,active,98,57.72,Card,2024-04-07,success,SUV,MH12AB1034
97,94,46,8,Hinjewadi,Wakad,2024-02-04 21:00:00,2024-02-04 21:20:00,336.13,completed,44,...,Sanjay Gaikwad,4.53,active,107,167.40,Card,2024-04-16,success,SUV,MH12AB1043
105,101,66,5,Shivajinagar,Hinjewadi,2024-02-05 04:00:00,2024-02-05 04:20:00,286.48,completed,1,...,Ashok Jadhav,4.58,active,114,474.75,Cash,2024-04-23,success,SUV,MH12AB1000
106,102,8,37,Kothrud,Kothrud,2024-02-05 05:00:00,2024-02-05 05:20:00,217.81,completed,2,...,Ajay Phadke,4.14,active,115,474.91,Card,2024-04-24,success,SUV,MH12AB1001
114,110,6,22,Kothrud,Hinjewadi,2024-02-05 13:00:00,NaT,323.12,ongoing,10,...,Laxmikant Jagtap,4.77,inactive,123,419.29,Cash,2024-05-02,success,SUV,MH12AB1009
127,122,84,23,Baner,Baner,2024-02-06 01:00:00,2024-02-06 01:20:00,344.56,completed,22,...,Madhav Nikam,4.59,active,135,223.43,UPI,2024-05-14,processing,SUV,MH12AB1021
131,126,79,38,Kothrud,Shivajinagar,2024-02-06 05:00:00,2024-02-06 05:20:00,294.31,cancelled,26,...,Baban Pawaskar,4.84,active,139,273.22,UPI,2024-05-18,failed,SUV,MH12AB1025
135,130,81,7,Shivajinagar,Kothrud,2024-02-06 09:00:00,NaT,594.79,ongoing,30,...,Pravin Chavan,4.97,active,143,67.63,Cash,2024-05-22,success,SUV,MH12AB1029
140,135,85,21,Wakad,Hinjewadi,2026-04-01 12:33:10,2024-02-06 14:20:00,231.99,booked,35,...,Kailas Gawade,4.45,active,148,305.83,Cash,2024-05-27,success,SUV,MH12AB1034

In [26]:
data9=df[(df["pickup_location"]=="Pune") & (df["drop_location"]=="Mumbai")]
data9

Empty DataFrame
Columns: [ride_id, customer_id, driver_id, pickup_location, drop_location, pickup_time, drop_time, fare, ride_status, vehicle_id, customer_name, phone, city, driver_name, rating, status_y, payment_id, amount, payment_method, payment_date, payment_status, vehicle_type, vehicle_number]
Index: []

[0 rows x 23 columns]

In [27]:
data10=df[(df["fare"]>200) & (df["payment_status"]=="success")]
data10

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,1,175.80,UPI,2024-01-01,success,SUV,MH12AB1000
1,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,32,325.18,UPI,2024-02-01,success,SUV,MH12AB1000
2,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2,...,Qasim Pathan,4.04,active,2,447.57,Cash,2024-01-02,success,SUV,MH12AB1001
4,4,7,20,Wakad,Shivajinagar,2024-02-01 03:00:00,2024-02-01 03:20:00,310.31,completed,4,...,Jagdish Kadam,4.30,active,4,478.88,Card,2024-01-04,success,Auto,MH12AB1003
5,5,66,18,Kothrud,Wakad,2024-02-01 04:00:00,2024-02-01 04:20:00,311.30,completed,5,...,Hanumant Pujari,3.76,active,5,198.84,UPI,2024-01-05,success,SUV,MH12AB1004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,169,6,17,Baner,Shivajinagar,2024-02-08 00:00:00,2024-02-08 00:20:00,428.86,completed,19,...,Ganpat Kamble,3.77,active,39,72.85,Cash,2024-02-08,success,Sedan,MH12AB1018
146,217,52,20,Baner,Kothrud,2024-02-10 00:00:00,2024-02-10 00:20:00,203.53,cancelled,17,...,Jagdish Kadam,4.30,active,41,62.43,Card,2024-02-10,success,Auto,MH12AB1016
147,241,80,24,Wakad,Baner,2024-02-11 00:00:00,2024-02-11 00:20:00,487.62,completed,41,...,Narayan Bhujbal,4.42,active,42,310.49,Cash,2024-02-11,success,Sedan,MH12AB1040
148,265,21,28,Kothrud,Hinjewadi,2024-02-12 00:00:00,2024-02-12 00:20:00,423.17,completed,15,...,Ravindra Patankar,3.84,active,43,247.31,Card,2024-02-12,success,SUV,MH12AB1014
149,289,3,38,Shivajinagar,Kothrud,2024-02-13 00:00:00,2024-02-13 00:20:00,527.94,completed,39,...,Baban Pawaskar,4.84,active,44,352.41,Cash,2024-02-13,success,Sedan,MH12AB1038

In [28]:
data11=df[(df["payment_method"]=="Cash") | (df["payment_method"]=="UPI")]
data11

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,1,175.80,UPI,2024-01-01,success,SUV,MH12AB1000
1,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,32,325.18,UPI,2024-02-01,success,SUV,MH12AB1000
2,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2,...,Qasim Pathan,4.04,active,2,447.57,Cash,2024-01-02,success,SUV,MH12AB1001
5,5,66,18,Kothrud,Wakad,2024-02-01 04:00:00,2024-02-01 04:20:00,311.30,completed,5,...,Hanumant Pujari,3.76,active,5,198.84,UPI,2024-01-05,success,SUV,MH12AB1004
6,6,95,20,Wakad,Kothrud,2024-02-01 05:00:00,2024-02-01 05:20:00,526.11,completed,6,...,Jagdish Kadam,4.30,active,6,298.74,Cash,2024-01-06,success,Mini,MH12AB1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,137,5,20,Baner,Shivajinagar,2024-02-06 16:00:00,2024-02-06 16:20:00,180.59,completed,37,...,Jagdish Kadam,4.30,active,150,379.24,UPI,2024-05-29,processing,Auto,MH12AB1036
144,169,6,17,Baner,Shivajinagar,2024-02-08 00:00:00,2024-02-08 00:20:00,428.86,completed,19,...,Ganpat Kamble,3.77,active,39,72.85,Cash,2024-02-08,success,Sedan,MH12AB1018
145,193,8,7,Wakad,Wakad,2024-02-09 00:00:00,2024-02-09 00:20:00,431.31,completed,43,...,Pravin Chavan,4.97,active,40,448.98,Cash,2024-02-09,refunded,Sedan,MH12AB1042
147,241,80,24,Wakad,Baner,2024-02-11 00:00:00,2024-02-11 00:20:00,487.62,completed,41,...,Narayan Bhujbal,4.42,active,42,310.49,Cash,2024-02-11,success,Sedan,MH12AB1040
149,289,3,38,Shivajinagar,Kothrud,2024-02-13 00:00:00,2024-02-13 00:20:00,527.94,completed,39,...,Baban Pawaskar,4.84,active,44,352.41,Cash,2024-02-13,success,Sedan,MH12AB1038

In [31]:
data12=df[(df["rating"]<3) | (df["rating"]>4.3)]
data12

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
7,7,71,30,Kothrud,Wakad,2024-02-01 06:00:00,2024-02-01 06:20:00,260.78,cancelled,7,...,Tukaram Ghodke,4.45,active,7,307.53,Cash,2024-01-07,success,Auto,MH12AB1006
9,9,75,23,Shivajinagar,Shivajinagar,2024-02-01 08:00:00,2024-02-01 08:20:00,353.98,completed,9,...,Madhav Nikam,4.59,active,9,83.91,Cash,2024-01-09,success,Mini,MH12AB1008
12,12,26,50,Hinjewadi,Hinjewadi,2024-02-01 11:00:00,2024-02-01 11:20:00,505.36,completed,12,...,Nilesh Pargaonkar,4.42,active,12,170.81,Card,2024-01-12,pending,Sedan,MH12AB1011
22,22,98,8,Baner,Shivajinagar,2024-02-01 21:00:00,2024-02-01 21:20:00,101.22,completed,22,...,Sanjay Gaikwad,4.53,active,22,164.37,Card,2024-01-22,success,SUV,MH12AB1021
24,24,18,48,Kothrud,Baner,2024-02-01 23:00:00,2024-02-01 23:20:00,492.65,completed,24,...,Lalit Patne,4.98,active,24,195.15,Cash,2024-01-24,pending,Mini,MH12AB1023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,135,85,21,Wakad,Hinjewadi,2026-04-01 12:33:10,2024-02-06 14:20:00,231.99,booked,35,...,Kailas Gawade,4.45,active,148,305.83,Cash,2024-05-27,success,SUV,MH12AB1034
143,145,36,39,Kothrud,Baner,2024-02-07 00:00:00,2024-02-07 00:20:00,409.46,completed,45,...,Chandrakant More,4.92,active,38,228.55,Card,2024-02-07,success,Auto,MH12AB1044
145,193,8,7,Wakad,Wakad,2024-02-09 00:00:00,2024-02-09 00:20:00,431.31,completed,43,...,Pravin Chavan,4.97,active,40,448.98,Cash,2024-02-09,refunded,Sedan,MH12AB1042
147,241,80,24,Wakad,Baner,2024-02-11 00:00:00,2024-02-11 00:20:00,487.62,completed,41,...,Narayan Bhujbal,4.42,active,42,310.49,Cash,2024-02-11,success,Sedan,MH12AB1040
149,289,3,38,Shivajinagar,Kothrud,2024-02-13 00:00:00,2024-02-13 00:20:00,527.94,completed,39,...,Baban Pawaskar,4.84,active,44,352.41,Cash,2024-02-13,success,Sedan,MH12AB1038

In [33]:
data13=df[(df["ride_status"]=="cancelled") | (df["ride_status"]=="ongoing")]
data13

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
7,7,71,30,Kothrud,Wakad,2024-02-01 06:00:00,2024-02-01 06:20:00,260.78,cancelled,7,...,Tukaram Ghodke,4.45,active,7,307.53,Cash,2024-01-07,success,Auto,MH12AB1006
10,10,77,47,Hinjewadi,Shivajinagar,2024-02-01 09:00:00,NaT,203.52,ongoing,10,...,Kiran Parab,4.22,active,10,187.56,Card,2024-01-10,success,SUV,MH12AB1009
14,14,14,49,Baner,Hinjewadi,2024-02-01 13:00:00,2024-02-01 13:20:00,335.31,cancelled,14,...,Mangesh Tare,4.28,active,14,217.71,UPI,2024-01-14,success,Mini,MH12AB1013
20,20,88,28,Baner,Kothrud,2024-02-01 19:00:00,NaT,88.05,ongoing,20,...,Ravindra Patankar,3.84,active,20,352.01,Cash,2024-01-20,refunded,Mini,MH12AB1019
21,21,64,43,Kothrud,Hinjewadi,2024-02-01 20:00:00,2024-02-01 20:20:00,224.41,cancelled,21,...,Gajanan Sathe,3.98,active,21,211.39,Card,2024-01-21,success,Mini,MH12AB1020
29,28,98,46,Hinjewadi,Wakad,2024-02-02 03:00:00,2024-02-02 03:20:00,304.83,cancelled,28,...,Jeevan Chougule,3.88,active,28,298.77,Card,2024-01-28,success,Sedan,MH12AB1027
31,30,3,27,Baner,Hinjewadi,2026-04-01 12:33:10,NaT,427.20,ongoing,30,...,Qasim Pathan,4.04,active,30,238.90,Card,2024-01-30,processing,SUV,MH12AB1029
36,35,36,9,Wakad,Wakad,2024-02-02 10:00:00,2024-02-02 10:20:00,271.86,cancelled,35,...,Nitin Bhosale,4.22,inactive,48,427.52,Card,2024-02-17,pending,SUV,MH12AB1034
41,40,74,40,Hinjewadi,Shivajinagar,2024-02-02 15:00:00,NaT,558.19,ongoing,40,...,Datta Barve,4.25,active,53,291.69,Card,2024-02-22,success,Auto,MH12AB1039
43,42,63,14,Wakad,Wakad,2024-02-02 17:00:00,2024-02-02 17:20:00,465.52,cancelled,42,...,Dhanraj Gite,3.59,active,55,422.54,Cash,2024-02-24,success,SUV,MH12AB1041
50,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,34,52.33,Cash,2024-02-03,success,SUV,MH12AB1048
51,49,4,11,Shivajinagar,Baner,2024-02-03 00:00:00,2024-02-03 00:20:00,373.14,cancelled,49,...,Anand Mane,4.01,active,62,364.78,UPI,2024-03-02,success,SUV,MH12AB1048
52,50,46,25,Hinjewadi,Wakad,2024-02-03 01:00:00,NaT,85.08,ongoing,50,...,Omprakash Gavhane,4.58,active,63,112.26,Cash,2024-03-03,success,Mini,MH12AB1049
58,56,58,9,Kothrud,Baner,2024-02-03 07:00:00,2024-02-03 07:20:00,530.49,cancelled,6,...,Nitin Bhosale,4.22,inactive,69,245.08,UPI,2024-03-09,success,Mini,MH12AB1005
62,60,86,21,Kothrud,Baner,2026-04-01 12:33:10,NaT,118.36,ongoing,10,...,Kailas Gawade,4.45,active,73,86.39,UPI,2024-03-13,success,SUV,MH12AB1009
65,63,57,48,Shivajinagar,Kothrud,2024-02-03 14:00:00,2024-02-03 14:20:00,184.44,cancelled,13,...,Lalit Patne,4.98,active,76,76.19,Cash,2024-03-16,success,Sedan,MH12AB1012
72,70,10,40,Shivajinagar,Shivajinagar,2024-02-03 21:00:00,NaT,333.95,ongoing,20,...,Datta Barve,4.25,active,83,337.22,Cash,2024-03-23,success,Mini,MH12AB1019
80,77,67,17,Hinjewadi,Baner,2024-02-04 04:00:00,2024-02-04 04:20:00,315.92,cancelled,27,...,Ganpat Kamble,3.77,active,90,121.39,Card,2024-03-30,processing,Sedan,MH12AB1026
83,80,49,44,Shivajinagar,Shivajinagar,2024-02-04 07:00:00,NaT,121.68,ongoing,30,...,Harish Karmarkar,4.12,active,93,91.31,Card,2024-04-02,success,SUV,MH12AB1029
87,84,56,16,Wakad,Wakad,2024-02-04 11:00:00,2024-02-04 11:20:00,313.73,cancelled,34,...,Firoz Shaikh,4.61,active,97,128.90,Card,2024-04-06,success,Mini,MH12AB1033
93,90,26,35,Shivajinagar,Baner,2026-04-01 12:33:10,NaT,292.92,ongoing,40,...,Yogendra Kshirsagar,4.14,inactive,103,342.40,UPI,2024-04-12,success,Auto,MH12AB1039
94,91,18,13,Baner,Hinjewadi,2024-02-04 18:00:00,2024-02-04 18:20:00,244.33,cancelled,41,...,Chetan Thorat,4.16,active,104,71.63,UPI,2024-04-13,success,Sedan,MH12AB1040
102,98,26,16,Hinjewadi,Kothrud,2024-02-05 01:00:00,2024-02-05 01:20:00,209.14,cancelled,48,...,Firoz Shaikh,4.61,active,111,292.72,Card,2024-04-20,success,Mini,MH12AB1047
104,100,68,46,Shivajinagar,Wakad,2024-02-05 03:00:00,NaT,338.73,ongoing,50,...,Jeevan Chougule,3.88,active,113,327.13,UPI,2024-04-22,success,Mini,MH12AB1049
114,110,6,22,Kothrud,Hinjewadi,2024-02-05 13:00:00,NaT,323.12,ongoing,10,...,Laxmikant Jagtap,4.77,inactive,123,419.29,Cash,2024-05-02,success,SUV,MH12AB1009
116,112,41,9,Baner,Shivajinagar,2024-02-05 15:00:00,2024-02-05 15:20:00,153.66,cancelled,12,...,Nitin Bhosale,4.22,inactive,125,419.19,Cash,2024-05-04,success,Sedan,MH12AB1011
123,119,45,47,Wakad,Wakad,2024-02-05 22:00:00,2024-02-05 22:20:00,307.22,cancelled,19,...,Kiran Parab,4.22,active,132,328.21,Card,2024-05-11,pending,Sedan,MH12AB1018
124,120,93,31,Shivajinagar,Shivajinagar,2026-04-01 12:33:10,NaT,522.41,ongoing,20,...,Umesh Shirole,3.64,active,133,201.45,Card,2024-05-12,success,Mini,MH12AB1019
131,126,79,38,Kothrud,Shivajinagar,2024-02-06 05:00:00,2024-02-06 05:20:00,294.31,cancelled,26,...,Baban Pawaskar,4.84,active,139,273.22,UPI,2024-05-18,failed,SUV,MH12AB1025
135,130,81,7,Shivajinagar,Kothrud,2024-02-06 09:00:00,NaT,594.79,ongoing,30,...,Pravin Chavan,4.97,active,143,67.63,Cash,2024-05-22,success,SUV,MH12AB1029
138,133,50,3,Wakad,Shivajinagar,2024-02-06 12:00:00,2024-02-06 12:20:00,433.49,cancelled,33,...,Dilip Deshmukh,3.84,active,146,296.59,Card,2024-05-25,success,Mini,MH12AB1032
146,217,52,20,Baner,Kothrud,2024-02-10 00:00:00,2024-02-10 00:20:00,203.53,cancelled,17,...,Jagdish Kadam,4.30,active,41,62.43,Card,2024-02-10,success,Auto,MH12AB1016

In [36]:
data14=df[(df["vehicle_type"]=="Sedan")| (df["vehicle_type"]=="Hatchback")]
data14

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
8,8,41,10,Hinjewadi,Wakad,2024-02-01 07:00:00,2024-02-01 07:20:00,547.96,completed,8,...,Vishal Patil,4.09,active,8,491.15,Card,2024-01-08,success,Sedan,MH12AB1007
11,11,77,3,Baner,Kothrud,2024-02-01 10:00:00,2024-02-01 10:20:00,218.71,completed,11,...,Dilip Deshmukh,3.84,active,11,135.91,Cash,2024-01-11,success,Sedan,MH12AB1010
12,12,26,50,Hinjewadi,Hinjewadi,2024-02-01 11:00:00,2024-02-01 11:20:00,505.36,completed,12,...,Nilesh Pargaonkar,4.42,active,12,170.81,Card,2024-01-12,pending,Sedan,MH12AB1011
13,13,8,9,Hinjewadi,Shivajinagar,2024-02-01 12:00:00,2024-02-01 12:20:00,413.63,completed,13,...,Nitin Bhosale,4.22,inactive,13,268.38,Cash,2024-01-13,success,Sedan,MH12AB1012
16,16,2,36,Hinjewadi,Kothrud,2024-02-01 15:00:00,2024-02-01 15:20:00,162.90,completed,16,...,Zakir Shaikh,3.97,active,16,429.90,Cash,2024-01-16,success,Sedan,MH12AB1015
18,18,79,27,Hinjewadi,Shivajinagar,2024-02-01 17:00:00,2024-02-01 17:20:00,421.37,completed,18,...,Qasim Pathan,4.04,active,18,81.69,Cash,2024-01-18,success,Sedan,MH12AB1017
19,19,57,42,Hinjewadi,Wakad,2024-02-01 18:00:00,2024-02-01 18:20:00,570.79,completed,19,...,Fakruddin Shaikh,3.67,inactive,19,144.01,UPI,2024-01-19,success,Sedan,MH12AB1018
25,25,89,8,Shivajinagar,Baner,2024-02-02 00:00:00,2024-02-02 00:20:00,347.84,driver_cancelled,25,...,Sanjay Gaikwad,4.53,active,25,431.90,Cash,2024-01-25,success,Sedan,MH12AB1024
26,25,89,8,Shivajinagar,Baner,2024-02-02 00:00:00,2024-02-02 00:20:00,347.84,driver_cancelled,25,...,Sanjay Gaikwad,4.53,active,33,86.72,Card,2024-02-02,success,Sedan,MH12AB1024
28,27,70,21,Baner,Baner,2024-02-02 02:00:00,2024-02-02 02:20:00,411.11,completed,27,...,Kailas Gawade,4.45,active,27,369.01,Cash,2024-01-27,success,Sedan,MH12AB1026
29,28,98,46,Hinjewadi,Wakad,2024-02-02 03:00:00,2024-02-02 03:20:00,304.83,cancelled,28,...,Jeevan Chougule,3.88,active,28,298.77,Card,2024-01-28,success,Sedan,MH12AB1027
40,39,55,4,Shivajinagar,Shivajinagar,2024-02-02 14:00:00,2024-02-02 14:20:00,508.93,completed,39,...,Ramesh Kulkarni,4.33,active,52,186.47,Cash,2024-02-21,success,Sedan,MH12AB1038
42,41,82,1,Kothrud,Kothrud,2024-02-02 16:00:00,2024-02-02 16:20:00,446.28,completed,41,...,Santosh Pawar,4.54,active,54,196.99,Card,2024-02-23,success,Sedan,MH12AB1040
44,43,68,8,Shivajinagar,Shivajinagar,2024-02-02 18:00:00,2024-02-02 18:20:00,294.70,completed,43,...,Sanjay Gaikwad,4.53,active,56,172.19,Card,2024-02-25,success,Sedan,MH12AB1042
60,58,100,34,Kothrud,Shivajinagar,2024-02-03 09:00:00,2024-02-03 09:20:00,328.19,completed,8,...,Xavier Dsouza,4.24,active,71,162.89,UPI,2024-03-11,success,Sedan,MH12AB1007
63,61,60,24,Baner,Baner,2024-02-03 12:00:00,2024-02-03 12:20:00,224.47,completed,11,...,Narayan Bhujbal,4.42,active,74,242.74,UPI,2024-03-14,success,Sedan,MH12AB1010
64,62,49,19,Hinjewadi,Wakad,2024-02-03 13:00:00,2024-02-03 13:20:00,275.51,completed,12,...,Imran Momin,4.30,active,75,359.82,Cash,2024-03-15,processing,Sedan,MH12AB1011
65,63,57,48,Shivajinagar,Kothrud,2024-02-03 14:00:00,2024-02-03 14:20:00,184.44,cancelled,13,...,Lalit Patne,4.98,active,76,76.19,Cash,2024-03-16,success,Sedan,MH12AB1012
68,66,5,20,Kothrud,Hinjewadi,2024-02-03 17:00:00,2024-02-03 17:20:00,501.08,completed,16,...,Jagdish Kadam,4.30,active,79,157.90,Card,2024-03-19,success,Sedan,MH12AB1015
70,68,57,7,Baner,Wakad,2024-02-03 19:00:00,2024-02-03 19:20:00,459.38,completed,18,...,Pravin Chavan,4.97,active,81,132.29,Cash,2024-03-21,success,Sedan,MH12AB1017
71,69,61,3,Shivajinagar,Hinjewadi,2024-02-03 20:00:00,2024-02-03 20:20:00,334.29,completed,19,...,Dilip Deshmukh,3.84,active,82,470.58,UPI,2024-03-22,failed,Sedan,MH12AB1018
78,75,80,8,Hinjewadi,Hinjewadi,2026-04-01 12:33:10,2024-02-04 02:20:00,284.82,booked,25,...,Sanjay Gaikwad,4.53,active,88,71.47,UPI,2024-03-28,success,Sedan,MH12AB1024
80,77,67,17,Hinjewadi,Baner,2024-02-04 04:00:00,2024-02-04 04:20:00,315.92,cancelled,27,...,Ganpat Kamble,3.77,active,90,121.39,Card,2024-03-30,processing,Sedan,MH12AB1026
81,78,11,8,Kothrud,Baner,2024-02-04 05:00:00,2024-02-04 05:20:00,287.21,completed,28,...,Sanjay Gaikwad,4.53,active,91,104.07,Cash,2024-03-31,success,Sedan,MH12AB1027
92,89,86,40,Shivajinagar,Baner,2024-02-04 16:00:00,2024-02-04 16:20:00,240.97,completed,39,...,Datta Barve,4.25,active,102,259.10,Cash,2024-04-11,success,Sedan,MH12AB1038
94,91,18,13,Baner,Hinjewadi,2024-02-04 18:00:00,2024-02-04 18:20:00,244.33,cancelled,41,...,Chetan Thorat,4.16,active,104,71.63,UPI,2024-04-13,success,Sedan,MH12AB1040
96,93,67,27,Wakad,Shivajinagar,2024-02-04 20:00:00,2024-02-04 20:20:00,436.03,completed,43,...,Qasim Pathan,4.04,active,106,449.01,Cash,2024-04-15,success,Sedan,MH12AB1042
112,108,93,21,Kothrud,Baner,2024-02-05 11:00:00,2024-02-05 11:20:00,92.04,completed,8,...,Kailas Gawade,4.45,active,121,107.83,UPI,2024-04-30,failed,Sedan,MH12AB1007
115,111,10,22,Wakad,Kothrud,2024-02-05 14:00:00,2024-02-05 14:20:00,282.28,completed,11,...,Laxmikant Jagtap,4.77,inactive,124,331.67,Cash,2024-05-03,success,Sedan,MH12AB1010
116,112,41,9,Baner,Shivajinagar,2024-02-05 15:00:00,2024-02-05 15:20:00,153.66,cancelled,12,...,Nitin Bhosale,4.22,inactive,125,419.19,Cash,2024-05-04,success,Sedan,MH12AB1011
117,113,69,26,Wakad,Baner,2024-02-05 16:00:00,2024-02-05 16:20:00,104.55,completed,13,...,Pandurang Bendre,3.98,active,126,343.17,Card,2024-05-05,success,Sedan,MH12AB1012
120,116,90,1,Hinjewadi,Shivajinagar,2024-02-05 19:00:00,2024-02-05 19:20:00,308.70,completed,16,...,Santosh Pawar,4.54,active,129,146.57,Cash,2024-05-08,success,Sedan,MH12AB1015
122,118,37,33,Baner,Baner,2024-02-05 21:00:00,2024-02-05 21:20:00,234.81,completed,18,...,Waseem Shaikh,4.15,active,131,67.53,Cash,2024-05-10,success,Sedan,MH12AB1017
123,119,45,47,Wakad,Wakad,2024-02-05 22:00:00,2024-02-05 22:20:00,307.22,cancelled,19,...,Kiran Parab,4.22,active,132,328.21,Card,2024-05-11,pending,Sedan,MH12AB1018
130,125,15,37,Hinjewadi,Kothrud,2024-02-06 04:00:00,2024-02-06 04:20:00,105.04,driver_cancelled,25,...,Ajay Phadke,4.14,active,138,167.31,Cash,2024-05-17,success,Sedan,MH12AB1024
132,127,24,14,Hinjewadi,Shivajinagar,2024-02-06 06:00:00,2024-02-06 06:20:00,536.44,completed,27,...,Dhanraj Gite,3.59,active,140,361.80,Card,2024-05-19,refunded,Sedan,MH12AB1026
133,128,63,37,Baner,Kothrud,2024-02-06 07:00:00,2024-02-06 07:20:00,352.91,completed,28,...,Ajay Phadke,4.14,active,141,206.75,Card,2024-05-20,success,Sedan,MH12AB1027
144,169,6,17,Baner,Shivajinagar,2024-02-08 00:00:00,2024-02-08 00:20:00,428.86,completed,19,...,Ganpat Kamble,3.77,active,39,72.85,Cash,2024-02-08,success,Sedan,MH12AB1018
145,193,8,7,Wakad,Wakad,2024-02-09 00:00:00,2024-02-09 00:20:00,431.31,completed,43,...,Pravin Chavan,4.97,active,40,448.98,Cash,2024-02-09,refunded,Sedan,MH12AB1042
147,241,80,24,Wakad,Baner,2024-02-11 00:00:00,2024-02-11 00:20:00,487.62,completed,41,...,Narayan Bhujbal,4.42,active,42,310.49,Cash,2024-02-11,success,Sedan,MH12AB1040
149,289,3,38,Shivajinagar,Kothrud,2024-02-13 00:00:00,2024-02-13 00:20:00,527.94,completed,39,...,Baban Pawaskar,4.84,active,44,352.41,Cash,2024-02-13,success,Sedan,MH12AB1038

In [40]:
data15=df[(df["city"]=="Pune") & (df["fare"]>300) & (df["ride_status"]=="completed")]
data15

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
12,12,26,50,Hinjewadi,Hinjewadi,2024-02-01 11:00:00,2024-02-01 11:20:00,505.36,completed,12,...,Nilesh Pargaonkar,4.42,active,12,170.81,Card,2024-01-12,pending,Sedan,MH12AB1011
19,19,57,42,Hinjewadi,Wakad,2024-02-01 18:00:00,2024-02-01 18:20:00,570.79,completed,19,...,Fakruddin Shaikh,3.67,inactive,19,144.01,UPI,2024-01-19,success,Sedan,MH12AB1018
23,23,4,42,Shivajinagar,Baner,2024-02-01 22:00:00,2024-02-01 22:20:00,499.86,completed,23,...,Fakruddin Shaikh,3.67,inactive,23,182.88,Cash,2024-01-23,success,Auto,MH12AB1022
28,27,70,21,Baner,Baner,2024-02-02 02:00:00,2024-02-02 02:20:00,411.11,completed,27,...,Kailas Gawade,4.45,active,27,369.01,Cash,2024-01-27,success,Sedan,MH12AB1026
42,41,82,1,Kothrud,Kothrud,2024-02-02 16:00:00,2024-02-02 16:20:00,446.28,completed,41,...,Santosh Pawar,4.54,active,54,196.99,Card,2024-02-23,success,Sedan,MH12AB1040
47,46,93,25,Baner,Shivajinagar,2024-02-02 21:00:00,2024-02-02 21:20:00,363.54,completed,46,...,Omprakash Gavhane,4.58,active,59,428.91,Card,2024-02-28,success,Auto,MH12AB1045
56,54,26,10,Baner,Wakad,2024-02-03 05:00:00,2024-02-03 05:20:00,446.36,completed,4,...,Vishal Patil,4.09,active,67,68.48,UPI,2024-03-07,failed,Auto,MH12AB1003
69,67,70,26,Hinjewadi,Kothrud,2024-02-03 18:00:00,2024-02-03 18:20:00,375.64,completed,17,...,Pandurang Bendre,3.98,active,80,92.24,Cash,2024-03-20,refunded,Auto,MH12AB1016
70,68,57,7,Baner,Wakad,2024-02-03 19:00:00,2024-02-03 19:20:00,459.38,completed,18,...,Pravin Chavan,4.97,active,81,132.29,Cash,2024-03-21,success,Sedan,MH12AB1017
75,73,70,30,Shivajinagar,Wakad,2024-02-04 00:00:00,2024-02-04 00:20:00,521.46,completed,23,...,Tukaram Ghodke,4.45,active,35,332.55,Cash,2024-02-04,success,Auto,MH12AB1022
76,73,70,30,Shivajinagar,Wakad,2024-02-04 00:00:00,2024-02-04 00:20:00,521.46,completed,23,...,Tukaram Ghodke,4.45,active,86,246.05,Cash,2024-03-26,success,Auto,MH12AB1022
82,79,4,47,Baner,Kothrud,2024-02-04 06:00:00,2024-02-04 06:20:00,590.63,completed,29,...,Kiran Parab,4.22,active,92,203.85,UPI,2024-04-01,success,Mini,MH12AB1028
84,81,4,30,Baner,Hinjewadi,2024-02-04 08:00:00,2024-02-04 08:20:00,301.18,completed,31,...,Tukaram Ghodke,4.45,active,94,92.37,Card,2024-04-03,success,Auto,MH12AB1030
90,87,50,50,Hinjewadi,Kothrud,2024-02-04 14:00:00,2024-02-04 14:20:00,389.59,completed,37,...,Nilesh Pargaonkar,4.42,active,100,413.11,Card,2024-04-09,refunded,Auto,MH12AB1036
128,123,82,16,Wakad,Wakad,2024-02-06 02:00:00,2024-02-06 02:20:00,528.07,completed,23,...,Firoz Shaikh,4.61,active,136,356.73,Card,2024-05-15,success,Auto,MH12AB1022
133,128,63,37,Baner,Kothrud,2024-02-06 07:00:00,2024-02-06 07:20:00,352.91,completed,28,...,Ajay Phadke,4.14,active,141,206.75,Card,2024-05-20,success,Sedan,MH12AB1027
141,136,91,29,Baner,Baner,2024-02-06 15:00:00,2024-02-06 15:20:00,513.68,completed,36,...,Shankar Waghmare,3.94,active,149,309.17,Card,2024-05-28,failed,Auto,MH12AB1035
143,145,36,39,Kothrud,Baner,2024-02-07 00:00:00,2024-02-07 00:20:00,409.46,completed,45,...,Chandrakant More,4.92,active,38,228.55,Card,2024-02-07,success,Auto,MH12AB1044
144,169,6,17,Baner,Shivajinagar,2024-02-08 00:00:00,2024-02-08 00:20:00,428.86,completed,19,...,Ganpat Kamble,3.77,active,39,72.85,Cash,2024-02-08,success,Sedan,MH12AB1018
147,241,80,24,Wakad,Baner,2024-02-11 00:00:00,2024-02-11 00:20:00,487.62,completed,41,...,Narayan Bhujbal,4.42,active,42,310.49,Cash,2024-02-11,success,Sedan,MH12AB1040

In [42]:
data16=df[(df["payment_status"]=="failed") & (df["payment_method"]=="Card")]
data16

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
99,96,9,42,Baner,Baner,2024-02-04 23:00:00,2024-02-04 23:20:00,529.98,completed,46,...,Fakruddin Shaikh,3.67,inactive,109,470.05,Card,2024-04-18,failed,Auto,MH12AB1045
139,134,81,22,Kothrud,Kothrud,2024-02-06 13:00:00,2024-02-06 13:20:00,293.34,completed,34,...,Laxmikant Jagtap,4.77,inactive,147,240.56,Card,2024-05-26,failed,Mini,MH12AB1033
141,136,91,29,Baner,Baner,2024-02-06 15:00:00,2024-02-06 15:20:00,513.68,completed,36,...,Shankar Waghmare,3.94,active,149,309.17,Card,2024-05-28,failed,Auto,MH12AB1035

In [44]:
data17=df[(df["rating"]<3)& (df["ride_status"]=="completed")]
data17

Empty DataFrame
Columns: [ride_id, customer_id, driver_id, pickup_location, drop_location, pickup_time, drop_time, fare, ride_status, vehicle_id, customer_name, phone, city, driver_name, rating, status_y, payment_id, amount, payment_method, payment_date, payment_status, vehicle_type, vehicle_number]
Index: []

[0 rows x 23 columns]

In [46]:
df["pickup_time"]=pd.to_datetime(df["pickup_time"])

In [48]:
df["drop_time"]=pd.to_datetime(df["drop_time"])

In [51]:
data18=df[df["pickup_time"].dt.hour>18]
data18

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
20,20,88,28,Baner,Kothrud,2024-02-01 19:00:00,NaT,88.05,ongoing,20,...,Ravindra Patankar,3.84,active,20,352.01,Cash,2024-01-20,refunded,Mini,MH12AB1019
21,21,64,43,Kothrud,Hinjewadi,2024-02-01 20:00:00,2024-02-01 20:20:00,224.41,cancelled,21,...,Gajanan Sathe,3.98,active,21,211.39,Card,2024-01-21,success,Mini,MH12AB1020
22,22,98,8,Baner,Shivajinagar,2024-02-01 21:00:00,2024-02-01 21:20:00,101.22,completed,22,...,Sanjay Gaikwad,4.53,active,22,164.37,Card,2024-01-22,success,SUV,MH12AB1021
23,23,4,42,Shivajinagar,Baner,2024-02-01 22:00:00,2024-02-01 22:20:00,499.86,completed,23,...,Fakruddin Shaikh,3.67,inactive,23,182.88,Cash,2024-01-23,success,Auto,MH12AB1022
24,24,18,48,Kothrud,Baner,2024-02-01 23:00:00,2024-02-01 23:20:00,492.65,completed,24,...,Lalit Patne,4.98,active,24,195.15,Cash,2024-01-24,pending,Mini,MH12AB1023
45,44,12,7,Hinjewadi,Wakad,2024-02-02 19:00:00,2024-02-02 19:20:00,116.45,completed,44,...,Pravin Chavan,4.97,active,57,484.36,Card,2024-02-26,success,SUV,MH12AB1043
47,46,93,25,Baner,Shivajinagar,2024-02-02 21:00:00,2024-02-02 21:20:00,363.54,completed,46,...,Omprakash Gavhane,4.58,active,59,428.91,Card,2024-02-28,success,Auto,MH12AB1045
48,47,76,39,Baner,Shivajinagar,2024-02-02 22:00:00,2024-02-02 22:20:00,403.40,completed,47,...,Chandrakant More,4.92,active,60,137.47,Cash,2024-02-29,processing,SUV,MH12AB1046
49,48,11,16,Hinjewadi,Hinjewadi,2024-02-02 23:00:00,2024-02-02 23:20:00,421.39,completed,48,...,Firoz Shaikh,4.61,active,61,235.11,UPI,2024-03-01,success,Mini,MH12AB1047
70,68,57,7,Baner,Wakad,2024-02-03 19:00:00,2024-02-03 19:20:00,459.38,completed,18,...,Pravin Chavan,4.97,active,81,132.29,Cash,2024-03-21,success,Sedan,MH12AB1017
71,69,61,3,Shivajinagar,Hinjewadi,2024-02-03 20:00:00,2024-02-03 20:20:00,334.29,completed,19,...,Dilip Deshmukh,3.84,active,82,470.58,UPI,2024-03-22,failed,Sedan,MH12AB1018
72,70,10,40,Shivajinagar,Shivajinagar,2024-02-03 21:00:00,NaT,333.95,ongoing,20,...,Datta Barve,4.25,active,83,337.22,Cash,2024-03-23,success,Mini,MH12AB1019
73,71,67,48,Shivajinagar,Hinjewadi,2024-02-03 22:00:00,2024-02-03 22:20:00,414.50,completed,21,...,Lalit Patne,4.98,active,84,282.51,Card,2024-03-24,pending,Mini,MH12AB1020
74,72,34,8,Shivajinagar,Baner,2024-02-03 23:00:00,2024-02-03 23:20:00,495.06,completed,22,...,Sanjay Gaikwad,4.53,active,85,345.70,Card,2024-03-25,success,SUV,MH12AB1021
95,92,59,43,Kothrud,Shivajinagar,2024-02-04 19:00:00,2024-02-04 19:20:00,445.22,completed,42,...,Gajanan Sathe,3.98,active,105,477.12,UPI,2024-04-14,processing,SUV,MH12AB1041
96,93,67,27,Wakad,Shivajinagar,2024-02-04 20:00:00,2024-02-04 20:20:00,436.03,completed,43,...,Qasim Pathan,4.04,active,106,449.01,Cash,2024-04-15,success,Sedan,MH12AB1042
97,94,46,8,Hinjewadi,Wakad,2024-02-04 21:00:00,2024-02-04 21:20:00,336.13,completed,44,...,Sanjay Gaikwad,4.53,active,107,167.40,Card,2024-04-16,success,SUV,MH12AB1043
98,95,11,41,Kothrud,Hinjewadi,2024-02-04 22:00:00,2024-02-04 22:20:00,364.02,completed,45,...,Eshwar Kale,4.44,active,108,56.89,Cash,2024-04-17,pending,Auto,MH12AB1044
99,96,9,42,Baner,Baner,2024-02-04 23:00:00,2024-02-04 23:20:00,529.98,completed,46,...,Fakruddin Shaikh,3.67,inactive,109,470.05,Card,2024-04-18,failed,Auto,MH12AB1045
120,116,90,1,Hinjewadi,Shivajinagar,2024-02-05 19:00:00,2024-02-05 19:20:00,308.70,completed,16,...,Santosh Pawar,4.54,active,129,146.57,Cash,2024-05-08,success,Sedan,MH12AB1015
121,117,51,23,Wakad,Wakad,2024-02-05 20:00:00,2024-02-05 20:20:00,429.12,completed,17,...,Madhav Nikam,4.59,active,130,219.77,Card,2024-05-09,success,Auto,MH12AB1016
122,118,37,33,Baner,Baner,2024-02-05 21:00:00,2024-02-05 21:20:00,234.81,completed,18,...,Waseem Shaikh,4.15,active,131,67.53,Cash,2024-05-10,success,Sedan,MH12AB1017
123,119,45,47,Wakad,Wakad,2024-02-05 22:00:00,2024-02-05 22:20:00,307.22,cancelled,19,...,Kiran Parab,4.22,active,132,328.21,Card,2024-05-11,pending,Sedan,MH12AB1018

In [53]:
data19=df[df["pickup_time"].dt.date==df["drop_time"].dt.date]
data19

,ride_id,customer_id,driver_id,pickup_location,drop_location,pickup_time,drop_time,fare,ride_status,vehicle_id,...,driver_name,rating,status_y,payment_id,amount,payment_method,payment_date,payment_status,vehicle_type,vehicle_number
0,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,1,175.80,UPI,2024-01-01,success,SUV,MH12AB1000
1,1,78,3,Shivajinagar,Baner,2024-02-01 00:00:00,2024-02-01 00:20:00,419.52,completed,1,...,Dilip Deshmukh,3.84,active,32,325.18,UPI,2024-02-01,success,SUV,MH12AB1000
2,2,9,27,Wakad,Wakad,2024-02-01 01:00:00,2024-02-01 01:20:00,535.84,completed,2,...,Qasim Pathan,4.04,active,2,447.57,Cash,2024-01-02,success,SUV,MH12AB1001
3,3,79,40,Hinjewadi,Shivajinagar,2024-02-01 02:00:00,2024-02-01 02:20:00,121.44,completed,3,...,Datta Barve,4.25,active,3,386.47,Card,2024-01-03,success,Mini,MH12AB1002
4,4,7,20,Wakad,Shivajinagar,2024-02-01 03:00:00,2024-02-01 03:20:00,310.31,completed,4,...,Jagdish Kadam,4.30,active,4,478.88,Card,2024-01-04,success,Auto,MH12AB1003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,193,8,7,Wakad,Wakad,2024-02-09 00:00:00,2024-02-09 00:20:00,431.31,completed,43,...,Pravin Chavan,4.97,active,40,448.98,Cash,2024-02-09,refunded,Sedan,MH12AB1042
146,217,52,20,Baner,Kothrud,2024-02-10 00:00:00,2024-02-10 00:20:00,203.53,cancelled,17,...,Jagdish Kadam,4.30,active,41,62.43,Card,2024-02-10,success,Auto,MH12AB1016
147,241,80,24,Wakad,Baner,2024-02-11 00:00:00,2024-02-11 00:20:00,487.62,completed,41,...,Narayan Bhujbal,4.42,active,42,310.49,Cash,2024-02-11,success,Sedan,MH12AB1040
148,265,21,28,Kothrud,Hinjewadi,2024-02-12 00:00:00,2024-02-12 00:20:00,423.17,completed,15,...,Ravindra Patankar,3.84,active,43,247.31,Card,2024-02-12,success,SUV,MH12AB1014
149,289,3,38,Shivajinagar,Kothrud,2024-02-13 00:00:00,2024-02-13 00:20:00,527.94,completed,39,...,Baban Pawaskar,4.84,active,44,352.41,Cash,2024-02-13,success,Sedan,MH12AB1038

In [55]:
df["ride_location"]=df["drop_time"]-df["pickup_time"]

In [58]:
data20=df[df["ride_location"]>pd.Timedelta(hours=1)]
data20

Empty DataFrame
Columns: [ride_id, customer_id, driver_id, pickup_location, drop_location, pickup_time, drop_time, fare, ride_status, vehicle_id, customer_name, phone, city, driver_name, rating, status_y, payment_id, amount, payment_method, payment_date, payment_status, vehicle_type, vehicle_number, ride_location]
Index: []

[0 rows x 24 columns]

# 10 High-Value Analytical Questions for a Cab Booking System

In [62]:
# 1. What is the overall cancellation rate?
cancellation_rate=(df["ride_status"]=="cancelled").mean()*100
cancellation_rate

np.float64(12.666666666666668)

In [65]:
# 2. Which city generates the highest number of rides?
data=df["city"].value_counts()
data

city
Delhi        45
Pune         45
Bangalore    42
Mumbai       18
Name: count, dtype: int64

In [68]:
# 3. Which city generates the highest revenue?
d1=df.groupby("city")["fare"].sum().sort_values(ascending=False)
d1

city
Pune         16760.34
Delhi        15425.87
Bangalore    15036.95
Mumbai        6637.05
Name: fare, dtype: float64

In [70]:
# 4. What is the average fare per ride by vehicle type?
d2=df.groupby("vehicle_type")["fare"].mean().sort_values(ascending=False)
d2

vehicle_type
Mini     376.729143
Auto     373.125714
SUV      349.821026
Sedan    340.787073
Name: fare, dtype: float64

In [72]:
# 5. Which payment method is used most frequently?
d3=df["payment_method"].value_counts()
d3

payment_method
Cash    61
Card    49
UPI     40
Name: count, dtype: int64

In [77]:
# 6. What time of day has the highest ride demand?

df["hour"]=df["pickup_time"].dt.hour
d4=df["hour"].value_counts().sort_values(ascending=False)
d4

hour
0     19
12    15
13     6
4      6
6      6
7      6
9      6
10     6
1      6
3      6
15     6
16     6
2      5
5      5
8      5
11     5
18     5
19     5
21     5
22     5
17     4
20     4
23     4
14     4
Name: count, dtype: int64

In [80]:
# 7. Which drivers complete the most rides?
d5=df[df["ride_status"]=="completed"].groupby("driver_name")["ride_id"].count().sort_values(ascending=False)
d5

driver_name
Kailas Gawade        7
Datta Barve          7
Qasim Pathan         5
Dilip Deshmukh       5
Sanjay Gaikwad       5
Jagdish Kadam        4
Gajanan Sathe        4
Shankar Waghmare     3
Santosh Pawar        3
Tukaram Ghodke       3
Vishal Patil         3
Xavier Dsouza        3
Pravin Chavan        3
Nilesh Pargaonkar    3
Madhav Nikam         3
Kiran Parab          3
Ajay Phadke          3
Lalit Patne          3
Firoz Shaikh         3
Hanumant Pujari      3
Fakruddin Shaikh     3
Omprakash Gavhane    2
Pandurang Bendre     2
Chetan Thorat        2
Ravindra Patankar    2
Ramesh Kulkarni      2
Chandrakant More     2
Waseem Shaikh        2
Narayan Bhujbal      2
Laxmikant Jagtap     2
Ganpat Kamble        2
Bharat Salunkhe      1
Baban Pawaskar       1
Ashok Jadhav         1
Umesh Shirole        1
Imran Momin          1
Eknath Kharat        1
Dhanraj Gite         1
Eshwar Kale          1
Nitin Bhosale        1
Anand Mane           1
Zakir Shaikh         1
Name: ride_id, dtype: int64

In [82]:
# 8. What is the average ride duration?
df["ride_duration"]=df["drop_time"]-df["pickup_time"]
avg=df["ride_duration"].mean()
avg

Timedelta('-29 days +06:36:18.467153285')

In [83]:
# 9. Which routes are most popular?
df.groupby(["pickup_location","drop_location"])["ride_id"].count().sort_values(ascending=False)

pickup_location  drop_location
Shivajinagar     Baner            13
Baner            Baner            11
Hinjewadi        Wakad            10
                 Kothrud           8
                 Shivajinagar      8
Wakad            Wakad             8
Baner            Shivajinagar      8
                 Kothrud           7
                 Hinjewadi         7
Shivajinagar     Shivajinagar      7
Kothrud          Baner             7
Shivajinagar     Hinjewadi         7
Kothrud          Kothrud           6
Baner            Wakad             6
Kothrud          Hinjewadi         5
Wakad            Kothrud           5
Kothrud          Wakad             4
Wakad            Shivajinagar      4
Kothrud          Shivajinagar      3
Shivajinagar     Kothrud           3
                 Wakad             3
Wakad            Baner             3
                 Hinjewadi         3
Hinjewadi        Hinjewadi         3
                 Baner             1
Name: ride_id, dtype: int64

In [85]:
# 10. What percentage of payments fail?

(df["payment_status"]=="failed").mean()*100

np.float64(5.333333333333334)

In [86]:
df.to_csv("cab_rides_final.csv", index=False)